Refactor export structure
AntaresSimulatorTeam/Antares_Simulator pull request #1030
Opened 2022-12-20 08:30 UTC by guilpier-code

2022-12-20 08:55 UTC, guilpier-code commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> -        // TODO : for now empty constraints.txt file needed
Export file **constraints.txt** is empty and useless, so I removed it.
If it turns out to be useful at some point, we will add it easily.

2022-12-20 08:55 UTC, guilpier-code commented on src/solver/optimisation/opt_export_structure.cpp
> -void OPT_ExportInterco(const Antares::Data::Study& study,
Here we used to pass the whole study. This is unclear as we only need its writer.

2022-12-20 15:13 UTC, flomnes requested changes
LGTM

- Minor changes
- Files variable-x-y.txt are not identical

```
omnesflo@gm0winl370:~/short/029 Pumped storage plant - 2/output/20221220-1610eco$ md5sum variables-* | sort
3477bd34fe695d9e80bd31fa5b8ea266  variables-1-7.txt
3477bd34fe695d9e80bd31fa5b8ea266  variables-2-7.txt
3477bd34fe695d9e80bd31fa5b8ea266  variables-3-7.txt
3477bd34fe695d9e80bd31fa5b8ea266  variables-4-7.txt
3477bd34fe695d9e80bd31fa5b8ea266  variables-5-7.txt
68668da7fbb602eba00272eb60ed1c9b  variables-1-9.txt
68668da7fbb602eba00272eb60ed1c9b  variables-2-9.txt
68668da7fbb602eba00272eb60ed1c9b  variables-3-9.txt
68668da7fbb602eba00272eb60ed1c9b  variables-4-9.txt
68668da7fbb602eba00272eb60ed1c9b  variables-5-9.txt
6d91d159878c892dfd61782afd2879e5  variables-1-2.txt
6d91d159878c892dfd61782afd2879e5  variables-2-2.txt
6d91d159878c892dfd61782afd2879e5  variables-3-2.txt
6d91d159878c892dfd61782afd2879e5  variables-4-2.txt
6d91d159878c892dfd61782afd2879e5  variables-5-2.txt
8a87ecc7eabd35fd8ab30636ba853c6f  variables-1-8.txt
8a87ecc7eabd35fd8ab30636ba853c6f  variables-2-8.txt
8a87ecc7eabd35fd8ab30636ba853c6f  variables-3-8.txt
8a87ecc7eabd35fd8ab30636ba853c6f  variables-4-8.txt
8a87ecc7eabd35fd8ab30636ba853c6f  variables-5-8.txt
92409d8058efa6d42f734d758f2149e8  variables-1-6.txt
92409d8058efa6d42f734d758f2149e8  variables-2-6.txt
92409d8058efa6d42f734d758f2149e8  variables-3-6.txt
92409d8058efa6d42f734d758f2149e8  variables-4-6.txt
92409d8058efa6d42f734d758f2149e8  variables-5-6.txt
9afda112d33708ba0fe68365d59eaf6c  variables-1-10.txt
9afda112d33708ba0fe68365d59eaf6c  variables-2-10.txt
9afda112d33708ba0fe68365d59eaf6c  variables-3-10.txt
9afda112d33708ba0fe68365d59eaf6c  variables-4-10.txt
9afda112d33708ba0fe68365d59eaf6c  variables-5-10.txt
a3e7e5e5d7dcf3be5efad3a27e7caf5c  variables-1-4.txt
a3e7e5e5d7dcf3be5efad3a27e7caf5c  variables-2-4.txt
a3e7e5e5d7dcf3be5efad3a27e7caf5c  variables-3-4.txt
a3e7e5e5d7dcf3be5efad3a27e7caf5c  variables-4-4.txt
a3e7e5e5d7dcf3be5efad3a27e7caf5c  variables-5-4.txt
a4679b58d5d7899ccc48f1351ba6d48c  variables-1-11.txt
a4679b58d5d7899ccc48f1351ba6d48c  variables-2-11.txt
a4679b58d5d7899ccc48f1351ba6d48c  variables-3-11.txt
a4679b58d5d7899ccc48f1351ba6d48c  variables-4-11.txt
a4679b58d5d7899ccc48f1351ba6d48c  variables-5-11.txt
a47fd14f2c4a82c37c06774821cfaaab  variables-1-3.txt
a47fd14f2c4a82c37c06774821cfaaab  variables-2-3.txt
a47fd14f2c4a82c37c06774821cfaaab  variables-3-3.txt
a47fd14f2c4a82c37c06774821cfaaab  variables-4-3.txt
a47fd14f2c4a82c37c06774821cfaaab  variables-5-3.txt
bf3f9bd845f77d36f73a01d70ba1f2e8  variables-1-12.txt
bf3f9bd845f77d36f73a01d70ba1f2e8  variables-2-12.txt
bf3f9bd845f77d36f73a01d70ba1f2e8  variables-3-12.txt
bf3f9bd845f77d36f73a01d70ba1f2e8  variables-4-12.txt
bf3f9bd845f77d36f73a01d70ba1f2e8  variables-5-12.txt
d56b5b993a8b2af24d9e12cccb26582c  variables-1-5.txt
d56b5b993a8b2af24d9e12cccb26582c  variables-2-5.txt
d56b5b993a8b2af24d9e12cccb26582c  variables-3-5.txt
d56b5b993a8b2af24d9e12cccb26582c  variables-4-5.txt
d56b5b993a8b2af24d9e12cccb26582c  variables-5-5.txt
e376ce0ed270136fcd035d30a6a87340  variables-1-13.txt
e376ce0ed270136fcd035d30a6a87340  variables-2-13.txt
e376ce0ed270136fcd035d30a6a87340  variables-3-13.txt
e376ce0ed270136fcd035d30a6a87340  variables-4-13.txt
e376ce0ed270136fcd035d30a6a87340  variables-5-13.txt
fc3dcb76140f73a914f43f59c2eda27e  variables-1-1.txt
fc3dcb76140f73a914f43f59c2eda27e  variables-2-1.txt
fc3dcb76140f73a914f43f59c2eda27e  variables-3-1.txt
fc3dcb76140f73a914f43f59c2eda27e  variables-4-1.txt
fc3dcb76140f73a914f43f59c2eda27e  variables-5-1.txt
```

2022-12-20 15:13 UTC, flomnes commented on src/solver/optimisation/opt_export_structure.cpp
> +    std::string filename = "Variables.txt";
```suggestion
    std::string filename = "variables.txt";
```

2022-12-20 15:13 UTC, flomnes commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> +        OPT_ExportVariables(study->resultWriter, varname);
[Style] 
Writer = 1st argument, content = 2nd argument

2022-12-20 15:13 UTC, flomnes commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> +    bool doWeExport = exportStructure && firstWeekOfSimulation;
All these `bool` are `const`

2022-12-20 15:13 UTC, flomnes commented on src/libs/antares/study/fwd.cpp
> +    case mpsExportStatus::EXPORT_SECOND_OPTIM:
Nobody ever noticed that typo, good job !

2022-12-22 10:30 UTC, guilpier-code commented
> 
blabla

2022-12-22 10:37 UTC, guilpier-code commented
About the **variables-<year>-<week>.txt** : 
these files only differ because of the last piece of information on each line.
This last piece is the hour in the year.
So **variables-1-1.txt** and **variables-1-2.txt** are different.
But **variables-1-1.txt** and **variables-2-1.txt** are not.

2022-12-29 09:22 UTC, flomnes approved these changes

2023-01-05 15:22 UTC, merged