[CI] Don't generate PDF doc
AntaresSimulatorTeam/Antares_Simulator pull request #1088
Opened 2023-01-13 14:53 UTC by payetvin

close #1085

2023-02-16 16:18 UTC, flomnes commented
Content of **NSISOutput.log**
```
# Run command: "C:/Program Files (x86)/NSIS/makensis.exe"  "D:/a/Antares_Simulator/Antares_Simulator/_build/_CPack_Packages/win64/NSIS/project.nsi"
# Output:
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh


Processing script file: "D:/a/Antares_Simulator/Antares_Simulator/_build/_CPack_Packages/win64/NSIS/project.nsi" (ACP)


File: "D:/a/Antares_Simulator/Antares_Simulator/_build\ui\simulator\resources\help\\antares-general-reference-guide.pdf" -> no files found.


Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |


   /oname=outfile one_file_only)


Error in macro File on macroline 3


Error in script "D:/a/Antares_Simulator/Antares_Simulator/_build/_CPack_Packages/win64/NSIS/project.nsi" on line 336 -- aborting creation process


```

2023-02-17 09:17 UTC, flomnes commented on .github/workflows/windows-vcpkg.yml
> +           touch antares-general-reference-guide.pdf system-map-editor-reference-guide.pdfi antares-examples-library.pdf
```suggestion
           touch antares-general-reference-guide.pdf system-map-editor-reference-guide.pdf antares-examples-library.pdf
```

2023-02-22 13:04 UTC, guilpier-code approved these changes

2023-02-22 13:07 UTC, flomnes requested changes
1. Revert changes related to accents & encoding
2. At the top of each file, introduce env variable `GENERATE_DOC`
```yaml
GENERATE_DOC: ${{ github.event_name == 'release' || startsWith(github.ref_name, 'doc/') }}
```
3. Revert changes in sourcefiles.inc.nsh

2023-02-22 13:07 UTC, flomnes commented on .github/workflows/centos7.yml
> +    if: ${{ github.event_name == 'release' || contains(github.ref_name, 'doc/') }}
```suggestion
    if: ${{ github.event_name == 'release' || startsWith(github.ref_name, 'doc/') }}
```
Slightly more accurate

2023-02-22 13:07 UTC, flomnes commented on src/distrib/win32/NSIS.template.in
> +;LangString LngInstallFull ${LANG_FRENCH}   "Complet (Recommand?)"
Revert this

2023-02-22 13:07 UTC, flomnes commented on src/distrib/win32/NSIS.template.in
> +;LangString LngWelcome ${LANG_FRENCH} "Bienvenue ? l'assistant d'installation d'Antares ${PRODUCT_VERSION}"
Revert this

2023-02-22 13:07 UTC, flomnes commented on src/distrib/win32/NSIS.template.in
> +VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "? ${PRODUCT_PUBLISHER}"
Revert

2023-02-22 13:07 UTC, flomnes commented on src/distrib/win32/sourcefiles.inc.nsh
> +File /nonfatal /r  ${ANTARES_SRC_DIR}\..\resources\*.*
Revert this

2023-03-02 12:38 UTC, flomnes approved these changes

2023-03-02 12:39 UTC, merged