Add coefficient for hurdle cost in the CSR problem
AntaresSimulatorTeam/Antares_Simulator pull request #1155
Opened 2023-02-08 10:52 UTC by flomnes

2023-02-14 15:19 UTC, guilpier-code requested changes

2023-02-14 15:19 UTC, guilpier-code commented on src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
>          {
The file **hourly_csr_problem.h** is not referenced in the any cmake file.
I just run a symbol search over the solution and realized that **hourly_csr_problem.h** was not searched in.

2023-02-14 15:19 UTC, guilpier-code commented on src/solver/simulation/sim_structure_probleme_economique.h
> +    static double computeHurdleCostCoefficient(double a, double b)
```C++
static double hurdleCostCoefficient(double unsuppThermalCost1, double unsuppThermalCost2)
{
    ....
}
```

2023-02-15 16:56 UTC, flomnes commented on src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
>          {
fixed in #1165

2023-02-16 13:53 UTC, guilpier-code approved these changes

2023-02-16 13:54 UTC, merged