Add adequacy patch optimization number to MPS filename to avoid overwrite
AntaresSimulatorTeam/Antares_Simulator pull request #1187
Opened 2023-02-23 15:02 UTC by flomnes

2023-03-01 15:47 UTC, guilpier-code requested changes

2023-03-01 15:47 UTC, guilpier-code commented on src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
> +    problemeHebdo_->adequacyPatchRuntimeData->LMR_FirstOptimization = true;
ok.
Should conflict with #1189

2023-03-01 15:47 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +    auto adqPatchOptNumber
Following the oral talk we just had, I think that the MPS filename should **not** be computed here, but at a higher in the call stack.
Here this name should be passed as an argument.
See this comment (not linked yet)

2023-03-01 15:47 UTC, guilpier-code commented on src/solver/optimisation/opt_optimisation_lineaire.cpp
> +              problemeHebdo, NumeroDeLIntervalle, optimizationNumber, *optPeriodStringGenerator))
Here we should have : 
```C++
auto mpsFileNames = MPSfileNames(problemeHebdo->OptimisationAuPasHebdomadaire,
                                 NumeroDeLIntervalle,
                                 problemeHebdo->adequacyPatchRuntimeData
                                 problemeHebdo->weekInTheYear,
                                 problemeHebdo->year)

if (!OPT_AppelDuSimplexe(problemeHebdo, 
                         NumeroDeLIntervalle, 
                         optimizationNumber, 
                         mpsFileNames->mps()))
            return false;

if (problemeHebdo->ExportMPS ......)
{
    ...
    OPT_EcrireResultatFonctionObjectiveAuFormatTXT(optimalSolutionCost,
                                                   mpsFileNames->criterion());
}
```

2023-03-01 16:28 UTC, guilpier-code requested changes

2023-03-01 16:28 UTC, guilpier-code commented on src/solver/optimisation/opt_period_string_generator_base.h
> +    std::string createOptimizationFilename(const std::string& title,
Base class **OptPeriodStringGenerator** is an abstraction for the optimization period, that is either :  
- \<year\>-\<week\>
- \<year\>-\<week\>-\<day\>

inside the filename.
So why do we have a new **createOptimizationFilename** function that take many arguments about the whole file name ?
I guess **OptPeriodStringGenerator** should concern the optimization period only.

2023-04-25 08:52 UTC, flomnes commented on src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
> +        && problemeHebdo->adequacyPatchRuntimeData->LMR_FirstOptimization)
```suggestion
    if (problemeHebdo->adequacyPatchRuntimeData
        && problemeHebdo->adequacyPatchRuntimeData->LMR_FirstOptimization)
```

2023-05-10 11:18 UTC, closed without merging