[CLEAN] Remove OUI_ANTARES NON_ANTARES
AntaresSimulatorTeam/Antares_Simulator pull request #1188
Opened 2023-02-24 13:01 UTC by payetvin

close #1144

2023-02-24 14:45 UTC, flomnes requested changes
LGTM. Remove the def of OUI_ANTARES and NON_ANTARES

2023-03-01 17:20 UTC, guilpier-code requested changes, later dismissed

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +    Probleme.FaireDuScaling = ( PremierPassage ? OUI_SPX : NON_SPX );
Why not make **FaireDuScaling** a boolean ?

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +    Probleme.AffichageDesTraces = ( PremierPassage ? OUI_SPX : NON_SPX );
Why not make **AffichageDesTraces** a boolean ?

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +    if (ProblemeAResoudre->ExistenceDUneSolution != OUI_SPX && PremierPassage)
why not make **ExistenceDUneSolution** a boolean ?

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
> +#if !VARIABLES_MMOINS_MOINS_BORNEES_DES_2_COTES
As the following block is never activated/compile, we should consider removing it

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
> +#if !VARIABLES_MMOINS_MOINS_BORNEES_DES_2_COTES
Remove one of these 2 alternatives ?

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/adequacy.cpp
> +        pProblemesHebdo[numSpace]->ReinitOptimisation = reinitOptim ? true : false;
```C++
pProblemesHebdo[numSpace]->ReinitOptimisation = reinitOptim;
```
should be enough

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +        pProblemesHebdo[numSpace]->ReinitOptimisation = reinitOptim ? true : false;
```C++
pProblemesHebdo[numSpace]->ReinitOptimisation = reinitOptim;
```
should be enough

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +        pProblemesHebdo[numSpace]->ReinitOptimisation = reinitOptim ? true : false;
Moreover, there are code duplication between **economy.cpp** and **adequacy.cpp**.
We should consider removing them.
For instance : 
```C++
catch (Data::UnfeasibleProblemError&)
{
    // need to clean next problemeHebdo
    reinitOptim = true;

    // Indicate failed week list (first week of the year is "week number one" for the
    // user but w=0 for the loop)
    failedWeekList.push_back(w + 1);

    // Define if simulation must be stopped
    if (Data::stopSimulation(study.parameters.include.unfeasibleProblemBehavior))
    {
          return false;
    }
}
```

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +    problem.Expansion = parameters.expansion ? true : false;
```C++
problem.Expansion = parameters.expansion;
```

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +          ? true
Same as above

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +          ? true
Same as above

2023-03-01 17:20 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +      = (parameters.simplexOptimizationRange == Data::sorWeek) ? true : false;
etc.

2023-03-02 15:02 UTC, flomnes requested changes

2023-03-02 15:02 UTC, flomnes commented on src/solver/optimisation/opt_constants.h
> +constexpr bool VARIABLES_MMOINS_MOINS_BORNEES_DES_2_COTES = true;
This decl becomes unused, please remove it

2023-03-02 15:02 UTC, flomnes commented on src/solver/simulation/sim_calcul_economique.cpp
> +               : false);
Please change
```cpp
bool myDecision = someCondition ? true : false;
```
to
```c
bool myDecision = someCondition;
```

2023-03-02 17:06 UTC, flomnes approved these changes

2023-03-02 17:09 UTC, merged