Refactor CBuilder::Update()
AntaresSimulatorTeam/Antares_Simulator pull request #1195
Opened 2023-03-03 13:06 UTC by payetvin

close #1166

2023-03-06 15:01 UTC, guilpier-code requested changes

2023-03-06 15:01 UTC, guilpier-code commented on src/solver/constraints-builder/cbuilder.cpp
> +            if (includeLoopFlow && !updateLinkLoopFlow(linkInfo, hour)) // check validity of loopflow against NTC
Instead of : 
```C++
for (uint x = 1; x < HOURS_PER_YEAR; x++)
{
    hour = x - 1;
    ...
}
```
We could have : 
```C++
for (uint hour = 0; hour < HOURS_PER_YEAR - 1; hour++)
{
    if (link->parameters[columnImpedance][hour + 1] != link->parameters[columnImpedance][hour])
    {
         impedances.insert(link->parameters[columnImpedance][hour + 1]);
    }
    ...
}
```

2023-03-08 08:11 UTC, flomnes commented on src/solver/constraints-builder/cbuilder.h
> +        double currentLineSign = 1;
It seems that those 2 variables weren't initialized before. I'm a bit surprised it didn't cause a segfault at line 161 for example.

2023-03-08 08:16 UTC, flomnes requested changes
Please revert changes due to encoding

2023-03-08 08:16 UTC, flomnes commented on src/solver/constraints-builder/cbuilder.h
> +        double currentLineSign = 1;
You can replace lines 178-179 with
```
states.emplace_back(impedances, time, pInfinite);
```
See [emplace_back](https://en.cppreference.com/w/cpp/container/vector/emplace_back)
The same goes for lines 191-192.

2023-03-30 13:27 UTC, flomnes approved these changes
This `emplace_back` vs. `push_back` thing is a bit strange, but the rest is OK

2023-04-03 14:12 UTC, guilpier-code requested changes

2023-04-03 14:12 UTC, guilpier-code commented on src/solver/constraints-builder/cbuilder.cpp
> +bool CBuilder::updateLinkLoopFlow(linkInfo* linkInfo, size_t hour)
Tell me if I'm wrong but in **updateLinkLoopFlow(...)**, I can't see any change (or update) on the link passed as argument. There are only checks here.
So, instead of  **updateLinkLoopFlow(...)**, why not call this member function **checkValidityOfNodalLoopFlow(...)** (or something like that) ?

2023-04-03 14:12 UTC, guilpier-code commented on src/solver/constraints-builder/cbuilder.cpp
> +bool CBuilder::updateLinkPhaseShift(linkInfo* linkInfo, size_t hour) const
About **updateLinkPhaseShift(...)** : 
This function does 2 different things : it actually updates the link's phase shift : 
```C++
if (link->parameters[Data::fhlPShiftMinus][hour] != link->parameters[Data::fhlPShiftPlus][hour])
{
    linkInfo->hasPShiftsEqual = false;
}
```
But it also makes a check (right after this block).
Finally, it is called : 
```C++
if (includePhaseShift && !updateLinkPhaseShift(linkInfo, hour))
    return false;
```

I recommend to : 
- keep the update block in **updateLinkPhaseShift(...)**, but remove the check part.
- Create a new function **checkLinkPhaseShift(...)**, move the use of **includePhaseShift** into it, as well as the check block.

Eventually we could have : 
```C++
updateLinkPhaseShift(...);
if (! checkLinkPhaseShift(...)) // check validity of phase-shift
     return false;
```

2023-04-03 14:12 UTC, guilpier-code commented on src/solver/constraints-builder/grid.hxx
> +        // retrait des arêtes (u,v) qui sont dan Ei et remplacement dans le graphe duliqué
Correction of spelling mistakes : 
```C++
// Retrait des arêtes (u,v) qui sont dans Ei, et remplacement dans le graphe dupliqué
```

2023-04-14 08:41 UTC, flomnes approved these changes

2023-04-14 09:49 UTC, guilpier-code approved these changes

2023-04-14 10:33 UTC, merged