Short term storage files loading
AntaresSimulatorTeam/Antares_Simulator pull request #1206
Opened 2023-03-09 12:31 UTC by payetvin

2023-03-09 13:04 UTC, guilpier-code requested changes

2023-03-09 13:04 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/container.cpp
>  bool Container::createUnitsFromIniFile(const std::string& path)
About class **Container** : 
There are many **Container** classes, there can be distinguished the namespace they belong to.
But still it would be more expressive to rename **ShortTermStorage::Container**  into **ShortTermStorage::STstorageInput**.

2023-03-09 13:04 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +            Unit unit;
About class **Unit** : 
we should rename it **STstorageCluster** in order to stick to the specification documentation.

2023-03-09 13:04 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +bool Unit::loadFromSection(const IniFile::Section& section)
we should put member functions of different classes in different source files, but it's probably already the plan

2023-03-09 13:06 UTC, payetvin commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +bool Unit::loadFromSection(const IniFile::Section& section)
Indeed I think each header will have it's cpp file

2023-03-09 16:02 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.cpp
>  bool Container::createUnitsFromIniFile(const std::string& path)
ok

2023-03-09 16:02 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +            Unit unit;
ok

2023-03-13 16:06 UTC, flomnes requested changes

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/area/list.cpp
> +            ret = area.shortTermStorage.createUnitsFromIniFile(buffer.c_str()) and ret;
```suggestion
            ret = area.shortTermStorage.createUnitsFromIniFile(buffer.to<std::string>()) and ret;
```

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/area/list.cpp
> +        for (auto i = areas.begin(); i != end; ++i)
```suggestion
        for (auto& [id, area] : areas)
```

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +
`storagesByIndex.reserve(storagesById.size())`

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/properties.cpp
> +    }
Compare to reservoirCapacity

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/properties.h
> +#include "../../../inifile.h"
```suggestion
#include <antares/inifile.h>
```

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/unit.cpp
> +    return properties.validate();
```suggestion
    return properties.validate() && series.validate();
```

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +#define SEP std::filesystem::path::preferred_separator
nice !

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/area/area.h
> +    ShortTermStorage::STstorageInput shortTermStorage;
Please avoid changing class definitions in the skeleton branch

See [this PR](https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1163)

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +    return ret;
Use [`std::all_of`](https://en.cppreference.com/w/cpp/algorithm/all_any_none_of)

2023-03-13 16:06 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.h
> +    bool validate();
Why not `const`?

2023-03-13 17:29 UTC, flomnes requested changes
We need default values if the user doesn't specify them. Or we need to make them mandatory

2023-03-14 14:24 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/properties.cpp
> +    {"Other", Group::Other}
There should be 5 "other" categories: Other_1, ..., Other_5

2023-03-15 13:46 UTC, payetvin commented on src/libs/antares/study/area/list.cpp
> +            ret = area.shortTermStorage.createUnitsFromIniFile(buffer.c_str()) and ret;
Doesn't compile

2023-03-15 17:05 UTC, merged