WIP: Feature/xpansion  split mps
AntaresSimulatorTeam/Antares_Simulator pull request #124
Opened 2021-01-21 07:39 UTC by guilpier-code

Antares for Xpansion : split MPS into fixed and variable part.

When asking Xpansion mode, the first week of the simulation dumps the fixed part of the first optimization problem on disk, and every week dumps the its own variable part of the optimization problem.

This PR regards more specially the split the division ot MPS data into its fixed part and variable part.

This PR is related to issue #121

2021-02-02 12:21 UTC, flomnes requested changes

2021-02-02 12:21 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +	Flot = study.createFileIntoOutputWithExtension("fixed-part", "mps", numSpace);
`createFileIntoOutputWithExtension` assumes that prefix (the first argument, here "fixed-part") is either "problem" or "criterion", see mps.cpp:65 for example.

Therefore file numbering for other prefixes such as "fixed-part" is not handled properly. Consequently, `createFileIntoOutputWithExtension` needs to be updated to handle prefix="fixed-part".

2021-02-02 12:21 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +			fprintf(Flot, "Writing fixed part of MPS data : le sens de la contrainte %c ne fait pas partie des sens reconnus\n", Pb->Sens[Cnt]);
Don't mix French and English

2021-02-02 12:21 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +	Flot = study.createFileIntoOutputWithExtension("variable-part", "mps", numSpace);
Same remark, prefix "variable-part" is not handled properly

2021-03-02 13:15 UTC, guilpier-code commented on src/libs/antares/study/mps.cpp
> +    static std::map<YString, int> count;
ok, i approve the fix made by @flomnes

2021-03-02 14:04 UTC, flomnes approved these changes

2022-01-07 10:23 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        SecondMembre = ProblemePourPne->SecondMembre;
PNE has been removed from the develop branch, this distinction is no longer necessary.

2022-04-19 07:29 UTC, closed without merging