Scratchpad refactoring
AntaresSimulatorTeam/Antares_Simulator pull request #1266
Opened 2023-04-26 15:27 UTC by payetvin

close #1261

2023-04-26 15:35 UTC, flomnes requested changes
One of the `*` in `mutable AreaScratchpad** scratchpad` was useless

2023-04-26 15:35 UTC, flomnes commented on src/libs/antares/study/area/area.h
> +    mutable std::vector<std::shared_ptr<AreaScratchpad>> scratchpad;
```suggestion
    mutable std::vector<AreaScratchpad> scratchpad;
```

2023-04-26 15:35 UTC, flomnes commented on src/libs/antares/study/runtime/runtime.cpp
> +        area.scratchpad = std::vector<std::shared_ptr<AreaScratchpad>>(area.nbYearsInParallel);
```suggestion
        area.scratchpad.reserve(area.nbYearsInParallel);
```

2023-04-26 15:35 UTC, flomnes commented on src/libs/antares/study/runtime/runtime.cpp
> +            area.scratchpad[numSpace] = std::make_shared<AreaScratchpad>(r, area);
```suggestion
            area.scratchpad.emplace_back(r, area);
```

2023-04-26 15:35 UTC, flomnes commented on src/solver/variable/state.hxx
> +    scratchpad = area->scratchpad[numSpace].get();
```suggestion
    scratchpad = &area->scratchpad[numSpace];
```

2023-04-26 15:36 UTC, flomnes commented on src/libs/antares/study/area/area.cpp
> +        ret += sizeof(scratchpad[0]) * scratchpad.size();
I think the former one was clearer

2023-04-27 12:46 UTC, flomnes approved these changes

2023-04-27 12:51 UTC, guilpier-code requested changes

2023-04-27 12:51 UTC, guilpier-code commented on src/libs/antares/study/area/scratchpad.cpp
> +AreaScratchpad::~AreaScratchpad() = default;
We should remove the destructor here, and make it a default one in the corresponding **.h** source file

2023-04-27 13:00 UTC, flomnes commented on src/libs/antares/study/area/scratchpad.cpp
> +AreaScratchpad::~AreaScratchpad() = default;
Placing all declarations in the header, and all definitions in the .cpp is good practice. I'd rather keep the way @payetvin did.

2023-04-27 13:04 UTC, guilpier-code approved these changes

2023-04-27 13:06 UTC, merged