st storage - fix modeler
AntaresSimulatorTeam/Antares_Simulator pull request #1267
Opened 2023-04-26 15:46 UTC by guilpier-code

This PR for a discussion on how we should handle the modeler regarding the short term storage functionality.

2023-04-26 16:50 UTC, flomnes requested changes

2023-04-26 16:50 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
> +                int storageIndex = 0;
It seems that storageIndex is always 0, right ?

2023-04-26 16:50 UTC, flomnes commented on src/solver/simulation/sim_calcul_economique.cpp
> +            int STindex = 0;
Same remark, STindex is always 0.

2023-04-27 06:20 UTC, guilpier-code commented on src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
> +                int storageIndex = 0;
It's incremented at the end of the loop, isn't it ?

2023-04-27 08:18 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +            int STindex = 0;
oops, corrected.

2023-04-27 13:54 UTC, flomnes approved these changes

2023-04-27 13:54 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Only renaming here

2023-04-27 13:54 UTC, flomnes commented on src/solver/simulation/sim_calcul_economique.cpp
In this function, you set `toInsert.globalIndex` to the global index, not the local index.

I agree with this change. Strange that we never found it, it shows that our tests are insufficient.

2023-04-27 13:56 UTC, flomnes commented on src/solver/simulation/sim_calcul_economique.cpp
Also, consider renaming `STindex` to `storageIndex` for consistency.

2023-05-03 13:06 UTC, payetvin approved these changes

2023-05-03 13:11 UTC, merged