Use ISO8601 for date format in the logs
AntaresSimulatorTeam/Antares_Simulator pull request #1303
Opened 2023-05-12 15:16 UTC by payetvin

#close 1300

2023-05-17 13:17 UTC, flomnes requested changes

2023-05-17 13:17 UTC, flomnes commented on src/ext/yuni/src/yuni/core/logs/decorators/time.cpp
> +    return buff;
Dangling reference to a variable allocated on the stack. I suggest passing buff to `WriteCurrentTimestampToBufferMinGW` instead.

2023-05-17 13:21 UTC, guilpier-code submitted a review, later dismissed

2023-05-17 13:21 UTC, guilpier-code commented on src/ext/yuni/src/yuni/core/logs/decorators/time.h
> +        out.write(Private::LogsDecorator::WriteCurrentTimestampToBufferMinGW(), 20);
**2023-05-17 14:03:18** contains 19 characters, not 20. 
It was the reason why CI failed on Windows.
Don't know why it does not fail on Linux, probably because **nul** chars are treated differently on Linux.

2023-05-24 14:11 UTC, flomnes reviewed
The timezone specifier is missing. If we used UTC, we could simply add "Z" at the end of the string.

However, we use the **local time**, so we'd have to append "+1" or "+2" depending on the period. The problem is that there seems to be no portable way to determine this in C/C++.

https://stackoverflow.com/questions/13804095/get-the-time-zone-gmt-offset-in-c

See https://fr.wikipedia.org/wiki/ISO_8601

2023-05-24 14:11 UTC, flomnes commented on src/ext/yuni/src/yuni/core/logs/decorators/time.cpp
> +    strftime(buffer, 32, "%F %T", &timeinfo);
```suggestion
    strftime(buffer, 32, "%FT%T", &timeinfo);
```

2023-05-24 14:11 UTC, flomnes commented on src/ext/yuni/src/yuni/core/logs/decorators/time.cpp
> +    ::strftime(buffer, 32, "%F %T",  ::localtime(&rawtime));
```suggestion
    ::strftime(buffer, 32, "%FT%T",  ::localtime(&rawtime));
```

2023-05-24 14:26 UTC, flomnes approved these changes

2023-05-24 14:28 UTC, merged