Split area
AntaresSimulatorTeam/Antares_Simulator pull request #1507
Opened 2023-08-04 14:46 UTC by JasonMarechal25

2023-08-04 14:57 UTC, flomnes requested changes

2023-08-04 14:57 UTC, flomnes commented on src/libs/antares/CMakeLists.txt
> +	${SRC_OBJECT}
Please remove this

2023-08-04 14:57 UTC, flomnes commented on src/ui/simulator/toolbox/input/renewable-cluster.h
> +#include "area.h"
Unnecessary ?

2023-08-04 15:29 UTC, JasonMarechal25 commented on src/ui/simulator/toolbox/input/renewable-cluster.h
> +#include "area.h"
It's area.h of toolbox, not of study

2023-08-07 07:02 UTC, sylvlecl requested changes
See comment: I don't think we should merge this in the current state, this introduces cyclic dependencies between libraries.
We need to be consistent between linked libraries and included headers. We need to identify best way to achieve this with cmake.

2023-08-07 07:02 UTC, sylvlecl commented on src/libs/antares/study/area/CMakeLists.txt
> +        ${CMAKE_SOURCE_DIR}/libs
These are cyclic dependencies:
the new area lib depends on includes from downstream libs (for example study.h) which themselves depend on the area lib.

We must avoid this, it defeats the purpose of having smaller libraries with clear dependencies.
(in particular, changing study.h will still trigger the rebuild of the area library).

So, we should either:
- not separate this lib
- separate it properly, with removal of reverse dependencies

We must take care of libraries depending **only** on headers from upstream libraries.
We need to find what's the best way to ensure this with cmake. In the best case, headers should come simply through the definition of linked libraries. cmake 3.23 introduced the feature of "files set" which allows to define properly public headers, it seems it was not so clear before that version. To be investigated !

2023-08-16 13:50 UTC, JasonMarechal25 commented
Closing to prevent conflict with existing PRs and redo following new guidelines

2023-08-16 13:50 UTC, closed without merging