Update SonarCloud to Java 17
AntaresSimulatorTeam/Antares_Simulator pull request #1514
Opened 2023-08-07 13:04 UTC by payetvin

close #1491

2023-08-07 14:43 UTC, flomnes requested changes

2023-08-07 14:43 UTC, flomnes commented on .github/workflows/sonarcloud.yml
> +      SONAR_SCANNER_VERSION: 5.0.1.3006 # Find the latest version in the "Linux" link on this page:
Do we need this ? Does the action not set it for us ?

Also, please keep `if: "!contains(github.event.head_commit.message, '[skip ci]')"`, it's a simple way to skip the CI for example when adding minor stuff such as comments.

2023-08-08 10:00 UTC, sylvlecl commented on .github/workflows/sonarcloud.yml
> +        uses: SonarSource/sonarcloud-github-c-cpp@v1
We can probably use v2: https://github.com/marketplace/actions/sonarcloud-scan-for-c-and-c

2023-08-09 08:02 UTC, flomnes commented on .github/workflows/sonarcloud.yml
>        - name: ccache
I believe caching is no loger required, the GH action does it for us now

2023-08-09 10:06 UTC, flomnes approved these changes

2023-08-09 10:06 UTC, merged