fix analyzer
AntaresSimulatorTeam/Antares_Simulator pull request #1527
Opened 2023-08-09 08:57 UTC by a-zakir

fix infeasible problems analyzer 
close #1472

2023-08-24 11:48 UTC, flomnes requested changes

2023-08-24 11:48 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +}
Use C++ classes instead of `enum` and `if..else`

2023-08-24 11:48 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +          solver, objective, bMin, bMax, costs, idxVar, varName, MATRIX_ELEMENT_TYPE::VARIABLE);
You may wrap this behavior into a namer, taking an `std::vector` as ctor argument.

```cpp
class VariableNamer {
VariableNamer(const std::vector<string>& names);
std::string getName(unsigned index);
};

static void transferVariables(MPSolver* solver,
                              const double* bMin,
                              const double* bMax,
                              const double* costs,
                              int nbVar
                              VariableNamer& namer);

```

Then you only need one version for `transferVariables` and `transferRows`, not 2.

2023-08-24 11:48 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +        std::string constraintName = NomDesContraintes[idxRow];
```suggestion
        const auto& constraintName = NomDesContraintes[idxRow];
```

2023-08-24 11:48 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +    if (problemeSimplexe->UseNamedProblems())
```suggestion
    Namer variableNamer(problemeSimplexe->VariableNames, problemeSimplexe->UseNamedProblems());
    Namer constraintNamer(problemeSimplexe->ConstraintNames, problemeSimplexe->UseNamedProblems());
    // Pass these namers to transferVariables and transferRows
```

2023-09-11 13:00 UTC, flomnes commented on src/solver/infeasible-problem-analysis/constraint.cpp
> +}
There are multiple issues with this approach
1. This function is not testes
2. There is no error management (what if there are no "<" and ">" ?)
3. You could use iterators instead ; find "<", find ">" and return the string between these 2 iterators

2023-09-11 15:11 UTC, a-zakir commented on src/solver/infeasible-problem-analysis/constraint.cpp
> +}
1. ok
2. ok
3. why not

2023-09-13 11:05 UTC, flomnes requested changes

2023-09-13 11:05 UTC, flomnes commented on src/solver/infeasible-problem-analysis/constraint.cpp
> +    const auto& str_end_iterator = str.end();
`str.begin` is actually shorter than `str_begin_iterator`, consider removing this alias reference

2023-09-14 12:03 UTC, flomnes approved these changes

2023-09-14 12:03 UTC, merged