Remove dynamic alloc of PROBLEME_HEBDO
AntaresSimulatorTeam/Antares_Simulator pull request #1554
Opened 2023-08-16 14:02 UTC by payetvin

2023-08-17 09:55 UTC, flomnes requested changes

2023-08-17 09:55 UTC, flomnes commented on src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
> +    PROBLEME_ANTARES_A_RESOUDRE* ProblemeAResoudre = problemeHebdo.ProblemeAResoudre;
From my understanding, `ProblemeAResoudre` is now a `unique_ptr`(see #1549). I recommend removing function `OPT_LiberationMemoireDuProblemeAOptimiser`.

2023-08-17 09:55 UTC, flomnes commented on src/solver/simulation/adequacy.cpp
> +    if (!pProblemesHebdo.empty())
No longer required

2023-08-17 09:55 UTC, flomnes commented on src/solver/utils/optimization_statistics.h
> +    OptimizationStatistics(const OptimizationStatistics &o)
```suggestion
    OptimizationStatistics(const OptimizationStatistics &rhs)
```

2023-08-17 10:15 UTC, sylvlecl requested changes
A few more improvements are possible now that we use the vector.
Also, let's try to follow "rule of 3/5".

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/adequacy.cpp
> +    if (!pProblemesHebdo.empty())
Simpler to remove this unnecessary check

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/adequacy.cpp
> +    if (!pProblemesHebdo.empty())
we can remove it

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/economy.cpp
> +    if (!pProblemesHebdo.empty())
we can remove this

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/economy.cpp
> +    if (!pProblemesHebdo.empty())
to be removed

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/sim_structure_probleme_economique.h
> +    PROBLEME_HEBDO& operator=(PROBLEME_HEBDO&& other) = default;
See "[rule of 5](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c21-if-you-define-or-delete-any-copy-move-or-destructor-function-define-or-delete-them-all)": let's define also explicitly the = operator as deleted, for clarity sake.

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/utils/optimization_statistics.h
> +    OptimizationStatistics(const OptimizationStatistics &o)
See "[rule of 5](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c21-if-you-define-or-delete-any-copy-move-or-destructor-function-define-or-delete-them-all)": for clarity sake,
let's define also copy operator and move operators (or delete them).

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/adequacy.cpp
>          for (uint numSpace = 0; numSpace < pNbMaxPerformedYearsInParallel; numSpace++)
we can now just iterate on the vector content, for example:
```cpp
for (auto& problem: pProblemesHebdo)
{
    pProblemesHebdo.TypeDOptimisation = OPTIMISATION_LINEAIRE;
}
```

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/adequacy.cpp
>          for (uint numSpace = 0; numSpace < pNbMaxPerformedYearsInParallel; numSpace++)
We can now just iterate on the vector content.

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/economy.cpp
>          for (uint numSpace = 0; numSpace < pNbMaxPerformedYearsInParallel; numSpace++)
We can now just iterate on the vector content.

2023-08-17 10:15 UTC, sylvlecl commented on src/solver/simulation/economy.cpp
>          for (uint numSpace = 0; numSpace < pNbMaxPerformedYearsInParallel; numSpace++)
We can now just iterate on the vector content.

2023-08-17 13:54 UTC, flomnes requested changes
The tests are failing on Windows, please investigate.

2023-08-21 08:24 UTC, flomnes requested changes
Add TODO note in economy.cpp / adequacy.cpp, about why we still need a "classic" loop to iterate on a `std::vector`.

2023-08-21 14:27 UTC, flomnes approved these changes

2023-08-23 15:50 UTC, sylvlecl approved these changes

2023-08-23 17:37 UTC, merged