Upgrade src/solver/hydro to C++
AntaresSimulatorTeam/Antares_Simulator pull request #1581
Opened 2023-08-22 14:09 UTC by payetvin

close #1575

2023-08-23 14:36 UTC, a-zakir approved these changes

2023-08-23 16:09 UTC, sylvlecl commented
What about adding namespaces to those files while we are on the topic of migrating those to C++ ?

2023-08-24 10:06 UTC, flomnes requested changes
There are still quite a few `free`, why ?

2023-08-24 10:06 UTC, flomnes commented on src/solver/hydro/daily/h2o_j_donnees_mensuelles.h
> +typedef struct
```suggestion
struct DONNEES_MENSUELLES
```

2023-08-24 10:06 UTC, flomnes commented on src/solver/hydro/daily/h2o_j_donnees_optimisation.h
> +    std::string Sens;
It's not really a string, more like `std::vector<char>`

2023-08-24 10:06 UTC, flomnes commented on src/solver/hydro/daily2/h2o2_j_donnees_mensuelles.h
> +{
Don't use `typedef` here

2023-09-01 13:20 UTC, flomnes approved these changes

2023-09-01 13:20 UTC, merged