Remove some containers in libs
AntaresSimulatorTeam/Antares_Simulator pull request #1804
Opened 2023-11-30 16:32 UTC by payetvin

#1487

2023-12-01 10:07 UTC, flomnes commented on src/libs/antares/study/parts/short-term-storage/container.cpp
> +    /* }); */
Uncomment ?

2023-12-08 15:13 UTC, guilpier-code requested changes

2023-12-08 15:13 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/cluster.h
> +    mutable Properties properties;
Not a fan of adding a **mutable** keyword here.
I guess **mutable** was put here because **Properties::validate()** both is now **const** and though changes some data member values : for some data members, we tolerate wrong values among the input data, but the code corrects these wrong values in order to make to simulation pass.
I talked to @flomnes about that, and we don't want to do that anymore :  
We should forbid these wrong values, and raise an error when we bump into such values.

2023-12-08 15:13 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/container.h
> +    std::vector<STStorageCluster> storagesByIndex;
Not sure **ByIndex** in **storagesByIndex** is necessary. 
We could call it merely **clusters**, like it's done everywhere else for thermal and renewable

2023-12-11 13:00 UTC, payetvin commented on src/libs/antares/study/parts/short-term-storage/cluster.h
> +    mutable Properties properties;
I will do this work in another pull request, there's some refactoring/fixing to do in sts
#1808

2023-12-11 13:00 UTC, payetvin commented on src/libs/antares/study/parts/short-term-storage/container.h
> +    std::vector<STStorageCluster> storagesByIndex;
Same

2023-12-11 15:40 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/cluster.h
> +    mutable Properties properties;
No problem for me.
But in this new issue's presentation (#1808), there is no reference to remarks of the current PR that remain to be taken care of.
So I will add an TODO item in this issue, and approuve the current one.

2023-12-11 15:42 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/cluster.h
> +    mutable Properties properties;
Will be taken care of in #1808

2023-12-11 15:43 UTC, guilpier-code commented on src/libs/antares/study/parts/short-term-storage/container.h
> +    std::vector<STStorageCluster> storagesByIndex;
Will be taken care of in #1808

2023-12-11 15:43 UTC, guilpier-code approved these changes

2023-12-11 15:46 UTC, merged