Use licence MPL 2.0 instead of GPL3_WITH_RTE-Exceptions
AntaresSimulatorTeam/Antares_Simulator pull request #1812
Opened 2023-12-08 13:04 UTC by flomnes

2023-12-12 09:32 UTC, flomnes commented
We need a major version for this, so that would be 9.0

2023-12-14 00:07 UTC, a-zakir commented
> This has been the largest search&replace in the history of search&replaces, maybe ever !

congrats m8

2023-12-14 00:08 UTC, a-zakir approved these changes
definitely agree!

2023-12-14 23:24 UTC, 0x62646f727465 requested changes
My review as the OSPO Director at RTE:

- [x] 0) Not only src subdirectroy, please consider the docs subdirectory and root md files also

Example for doc subdir: docs/reference-guide/12-attribution_notices.md presents GNU GPL informations.
Example for /*.md file: README.md 

- [x] 1) Correct the Copyright notice

Please respect this exact pattern:

Copyright (c) [FIRSTYEAR]-2023, RTE (https://www.rte-france.com)
See AUTHORS.txt
SPDX-License-Identifier: MPL-2.0
This file is part of Antares-Simulator, Adequacy and Performance assesment for interconnected energy networks.

[FIRSTYEAR] must be the oldest year of the copyright to consider in the updated file
As we are releasing a major version we will update the Copyright year
If you will release the 9.0 version after January 1st then it will be 2024
Warning: do not update the copyright of others (ex. Matsumoto's once)

- [x] 2) Correct the SPDX-License-Identifier from MPL<space>2.0 to MPL<dash>2.0

Please replace all "SPDX-License-Identifier: MPL 2.0" by "SPDX-License-Identifier: MPL-2.0"

- [ ] 3) Post commit please correct the published documentation

- [x] 3.a) Readthedocs.io

Correct Flags from GPLv3 to MPLv2
Replace GPL V3 by MPL V2

- [x] at https://antares-simulator.readthedocs.io/en/latest/
After the line "In May 2018 RTE decided to release the project under the GPLv3 license."
Add the line "In [DATE], RTE, as the exclusive Copyright owner decided, to switch from GPL V3 to MPL V2 License since the 9.0 major version of Antares-Simulator"

- [ ] 3.b) https://antares-simulator.org/

- [x] 4) Exclude src/ext/yuni

No changes should be made in license.md

- [x] 5) Double check src/libs/antares/*

For example, Merseen-Twister appears to be a BSD Licence and there's no reference to it

- [ ] 6) commit and commit comment

The Version 9.0 changelog should be dedicated to the License change
No feature should be mixed with. A 9.1 version will.

The comment of this commit should precise:
As of [YYYY/MM/DD], RTE Group, holding exclusive copyright rights, has announced a significant update in their software licensing policy for Antares-Simulator. With the release of the major 9.0 version of Antares-Simulator, RTE Group is transitioning from the GNU General Public License Version 3 (GPLv3) to the Mozilla Public License Version 2.0 (MPL V2.0). This strategic move reflects RTE Group's ongoing commitment to fostering an open, collaborative development environment while ensuring a balanced approach to copyright management and distribution flexibility.

2024-01-02 13:53 UTC, JasonMarechal25 commented
What about files without licence head ?

2024-02-02 08:52 UTC, flomnes commented on src/libs/antares/benchmarking/DurationCollector.cpp
> +** distribution
Remove

2024-02-02 08:52 UTC, flomnes commented on .gitignore
> +tags
Revert

2024-02-02 10:22 UTC, merged