hydro max power : adding unit tests
AntaresSimulatorTeam/Antares_Simulator pull request #1843
Opened 2023-12-22 09:47 UTC by guilpier-code

2023-12-27 14:53 UTC, flomnes requested changes

2023-12-27 14:53 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	study->runtime->rangeLimits.year[rangeCount] = nbYears - 1;
This seems inconsistent with the previous 0 and 1

2023-12-27 14:53 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	BOOST_CHECK(Generate(*study));
What is `Generate` ? It seems quite vague in this context, maybe use the full name ?

2023-12-27 14:53 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	area_2->resizeAllTimeseriesNumbers(1 + study->runtime->rangeLimits.year[rangeEnd]);
Isn't there a function to do all this resizing for us ?

2024-03-13 15:33 UTC, flomnes commented on src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.h
This file was moved to src/libs/antares/study/include/antares/study/parts/hydro/hydromaxtimeseriesreader.h

2024-03-13 15:33 UTC, flomnes commented on docs/reference-guide/13-file-format.md
Work ongoing for the documentation. Please revert this.

2024-03-13 15:33 UTC, flomnes commented on src/libs/antares/study/scenario-builder/HydroMaxPowerTSNumberData.h
This file was moved to src/libs/antares/study/include/antares/study/scenario-builder/HydroMaxPowerTSNumberData.h

2024-03-13 15:33 UTC, flomnes commented on src/solver/simulation/sim_calcul_economique.cpp
> +                auto& area = *study.areas.byIndex[k];
Don't add spaces

2024-03-13 15:33 UTC, flomnes commented on src/solver/simulation/timeseries-numbers.cpp
> +
Duplicate of lines 311-317 above

```suggestion
```

2024-03-14 09:06 UTC, guilpier-code commented on docs/reference-guide/03-commands.md
> +  Regarding Hydro time-series, the scenario builder gives, in addition to the assignment of a specific number to use for the inflows time-series, the ability to define the initial reservoir level to
Comment from a review before update with **develop** (when this change appeared) :
This text addition makes the sentence very long and this piece of documentation unclear.
We should prefer something like : 

```txt
Regarding Hydro time-series, the scenario builder allows the user to choose, for a given year and area, a different time series whether we consider : 
- inflows, ROR and minimum generation
- initial level
- max power for generation and pumping
This implies that, inside one of the previous categories, the number of available time series is the same  
```

2024-03-14 09:06 UTC, guilpier-code commented on docs/reference-guide/04-active_windows.md
> +    ROR time-series and SP time-series may come from any origin outside Antares, or may have been formerly generated by the Antares time-series stochastic generator and stored as input data on the us
Comment from a review before update with **develop** (when this change appeared) :
"The **SP** time-series" : 
I guess **SP** stands for inflows or hydro storage (in **Antares**, it means the same thing [very unfortunate indeed, these 2 things should not be equivalent, because in real life, they aren't]).
I have never heard about **SP**.
So let's be more clear : rename SP into **hydro storage**

2024-03-14 09:06 UTC, guilpier-code commented on docs/reference-guide/04-active_windows.md
> +    ROR time-series are defined at the hourly scale; each of the 8760 values represents the ROR power expected at a given hour, expressed in round number and in MW. The SP time-series are defined at
Comment from a review before update with **develop** (when this change appeared) :
starting from "The Minimum Generation time-series..." : 
Following 3 phrases are the same, except for the quantity they concern.
One phrase is enough. Just add : "same for max generation and pumping power"

2024-03-14 09:06 UTC, guilpier-code commented on src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.h
This header was removed

2024-03-14 09:06 UTC, guilpier-code commented on docs/reference-guide/13-file-format.md
reverted

2024-03-14 09:06 UTC, guilpier-code commented on src/libs/antares/study/scenario-builder/HydroMaxPowerTSNumberData.h
additional header removed

2024-03-14 09:06 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +                auto& area = *study.areas.byIndex[k];
Space removed

2024-03-14 09:06 UTC, guilpier-code commented on src/solver/simulation/timeseries-numbers.cpp
> +
Duplication removed

2024-03-14 10:00 UTC, guilpier-code commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	study->runtime->rangeLimits.year[rangeCount] = nbYears - 1;
Actually, we don't need `study->runtime->rangeLimits.year[rangeCount]` : it's unused here, and inside tested function **Generate(...)**.
So I remove its initialization.

2024-03-14 10:16 UTC, flomnes commented on docs/reference-guide/03-commands.md
> +  Regarding Hydro time-series, the scenario builder gives, in addition to the assignment of a specific number to use for the inflows time-series, the ability to define the initial reservoir level to
See #1990

2024-03-14 10:31 UTC, guilpier-code commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	BOOST_CHECK(Generate(*study));
I will replace call to **Generate** with call to **TimeSeriesNumbers::Generate**.
But I think we should remove namespace **TimeSeriesNumbers**, overkill to me (is a new nested namespace necessary for 2 free functions, especially if they are named correctly ?), and rename **Generate** into **GenerateTSnumbers**.

2024-03-14 10:35 UTC, guilpier-code commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	BOOST_CHECK(Generate(*study));
Besides, why not change other calls to  **Generate** in the same way ?

2024-03-14 13:58 UTC, flomnes commented on src/solver/simulation/timeseries-numbers.cpp
> +            tsNumbersMtx = &(area.hydro.series->timeseriesNumbersHydroMaxPower);
👍🏻

2024-03-14 13:58 UTC, flomnes commented on src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
> +
Duplicate of lines above ⬆️

2024-03-14 13:58 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	BOOST_CHECK(Generate(*study));
I kind of like `Namespace::Generate`, I find it beautiful

2024-03-14 14:59 UTC, guilpier-code commented on src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
> +
Duplicated lines removed

2024-03-14 15:48 UTC, flomnes commented on src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
> +
⬇️  Duplicate of lines 113-116

2024-03-14 16:25 UTC, guilpier-code commented on src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
> +
Duplicate lines removed

2024-03-14 20:23 UTC, flomnes approved these changes

2024-03-14 20:23 UTC, merged