Change version behavior to allow more flexibility
AntaresSimulatorTeam/Antares_Simulator pull request #1898
Opened 2024-01-24 13:57 UTC by payetvin

close  #1743

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/area/links.cpp
> +    if (study.header.version < VersionStruct(8, 2))
```suggestion
    if (study.header.version < StudyVersion(8, 2))
```

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/cleaner/cleaner.cpp
> +    if (version == versionUnknown)
```suggestion
    if (version.isUnknown())
```

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/load.cpp
> +    logs.info() << "  detected version: " << header.version.toString();
```suggestion
    logs.info() << "  detected study version: " << header.version.toString();
```

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/load.cpp
> +    logs.info() << "  detected version: " << header.version.toString();
Please note that this log will change 
previous 880
now 8.8

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/output.cpp
> +    return version <= Data::versionLatest;
```suggestion
    return version <= StudyVersion::latest();
```
(static data member ?)

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/parameters.cpp
> +                                    VersionStruct& version)
```suggestion
                                    const VersionStruct& version)
```

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/version.cpp
> +};
Remove enum, remove this map ?

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/version.cpp
> +}
Add lots of unit-testing to this parser. Parsers can be nasty

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/version.h
> +static std::vector<std::string> supportedVersions =
```suggestion
static std::vector<StudyVersion> supportedVersions =
```

2024-01-25 14:48 UTC, flomnes commented on src/libs/antares/study/version.h
> +    unsigned minor = 0;
```suggestion
    const unsigned major = 0;
    const unsigned minor = 0;
```

2024-01-25 14:48 UTC, flomnes commented on src/tools/updater/main.cpp
> +        if (version == Data::versionUnknown || version > Data::versionLatest)
```suggestion
        if (!version.isValid())
```

2024-01-29 11:22 UTC, flomnes requested changes
Add some unit testing

`assert (StudyVersion(3,4) > StudyVersion(3,3))`

etc.

2024-01-29 11:22 UTC, flomnes commented on src/libs/antares/study/version.h
> +    StudyVersion() = default;
Is this required ?

2024-01-29 11:22 UTC, flomnes commented on src/libs/antares/study/version.h
> +    StudyVersion(const std::string&);
Is this required ? What happens if the conversion from a string fails ?

2024-01-29 11:22 UTC, flomnes commented on src/libs/antares/study/version.h
> +    StudyVersion(unsigned, unsigned);
OK

2024-01-29 11:22 UTC, flomnes commented on src/analyzer/atsp/load.cpp
> +    if (v > Data::StudyVersion::versionLatest())
```suggestion
    if (v > Data::StudyVersion::latest())
```

2024-01-29 11:22 UTC, flomnes commented on src/libs/antares/checks/checkLoadedInputData.cpp
> +    if (version == StudyVersion::versionUnknown())
```suggestion
    if (version == StudyVersion::unknown())
```

2024-01-29 11:22 UTC, flomnes commented on src/libs/antares/study/header.cpp
> +    return "0.0";
I don't like this hard-coded string.

2024-01-29 11:22 UTC, flomnes commented on src/libs/antares/study/header.cpp
> +    return "0.0";
I don't like this hard-coded string.

2024-01-29 17:18 UTC, flomnes commented on src/libs/antares/study/version.cpp
> +};
std::vector<StudyVersion> supportedVersions = {StudyVersion(7,0), ...};

2024-01-29 17:18 UTC, flomnes commented on src/libs/antares/study/version.cpp
> +    if (not directory.empty() and IO::Directory::Exists(directory))
This is I/O stuff, it belongs in a study reader

2024-01-29 17:18 UTC, flomnes commented on src/libs/antares/study/version.h
> +    unsigned minor = 0;
```suggestion
    const unsigned major = 0;
    const unsigned minor = 0;
```

2024-01-29 17:31 UTC, a-zakir commented on src/analyzer/atsp/load.cpp
>          logs.error() << "The folder is not a study";
the log message could be "could not identify the study version"

2024-01-29 17:33 UTC, a-zakir commented on src/analyzer/atsp/load.cpp
>          logs.error() << "The format of the study folder requires a more recent version of Antares";
also it could be "the study require "required" version or downgrade to "<<Data::StudyVersion::latest()

2024-01-29 17:38 UTC, a-zakir commented on src/libs/antares/study/finder/finder.h
> +    virtual void onStudyFound(const Yuni::String& folder, StudyVersion version) = 0;
const StudyVersion& version?

2024-01-29 17:45 UTC, a-zakir commented on src/libs/antares/study/parameters.h
>      */
nice doxygen doc already written please update it

2024-01-29 17:53 UTC, a-zakir commented on src/tests/src/libs/antares/study/test_study.cpp
> +
need test with v = XY.Y
X.YZ?

2024-01-29 17:55 UTC, a-zakir commented on src/tools/updater/main.cpp
>              logs.info() << folder << " : version of study is too old, too new or unknown";
not too old

2024-01-30 09:56 UTC, payetvin commented on src/libs/antares/study/version.h
> +    unsigned minor = 0;
Not const as we parse and attribute a value in the constructor
Members are private, removing the risk of modifying the values outside the class

2024-01-30 15:05 UTC, payetvin commented on src/libs/antares/study/version.cpp
> +    if (not directory.empty() and IO::Directory::Exists(directory))
done

2024-01-30 16:16 UTC, a-zakir approved these changes

2024-02-02 08:51 UTC, flomnes commented on src/libs/antares/study/cleaner.h
> +    std::string versionString;
```suggestion
```

2024-02-02 08:51 UTC, flomnes commented on src/libs/antares/study/cleaner/cleaner.cpp
> +    version = StudyVersion::unknown();
Useless

2024-02-02 08:51 UTC, flomnes commented on src/libs/antares/study/cleaner/cleaner.cpp
> +    version = StudyVersion::unknown();
Useless

2024-02-02 08:51 UTC, flomnes commented on src/libs/antares/study/version.cpp
> +/*** Copyright 2007-2023 RTE
Typo

2024-02-02 10:37 UTC, flomnes approved these changes

2024-02-02 10:48 UTC, merged