Add total time logging at the end of the simulation
AntaresSimulatorTeam/Antares_Simulator pull request #1908
Opened 2024-01-31 16:13 UTC by payetvin

close  #1907

2024-01-31 17:27 UTC, a-zakir approved these changes

2024-01-31 17:31 UTC, a-zakir commented
sonar complains about sprintf...

2024-01-31 21:25 UTC, flomnes requested changes

2024-01-31 21:25 UTC, flomnes commented on src/solver/application/application.cpp
> +    sprintf(timeDisplay, "%02uh%02um%02us", hours, minutes, seconds);
Use snprintf to avoid possible overflow

2024-01-31 21:25 UTC, flomnes commented on src/solver/application/application.cpp
> +    unsigned hours = duration / 3600;
Consider using std::chrono, do not re-invent the wheel

2024-02-01 12:18 UTC, flomnes commented on src/solver/application/application.cpp
> +    snprintf(timeDisplay, 10, "%02luh%02lum%02lus", hours.count(), minutes.count(), seconds.count());
Actually, you don't even need to bother with `snprintf`, you can use

```cpp
logs.info().appendFormat(format, args);
```

See for example **src/solver/optimisation/opt_appel_solveur_quadratique.cpp**
```cpp
logs.info().appendFormat("Variable %ld cout lineaire %e  cout quadratique %e",
                         i,
                         ProblemeAResoudre->CoutLineaire[i],
                         ProblemeAResoudre->CoutQuadratique[i]);
```

2024-02-01 14:27 UTC, flomnes approved these changes

2024-02-01 14:48 UTC, merged