WIP : Features/move antares deps and test
AntaresSimulatorTeam/Antares_Simulator pull request #198
Opened 2021-03-04 17:14 UTC by jmkerloch

2021-04-01 12:03 UTC, flomnes commented on src/distrib/win32/sourcefiles.inc.nsh
> -
No longer include test studies to the Windows installer ? Is this intended ?

2021-04-01 12:03 UTC, flomnes commented on src/tests/examples/example_test.py
> +ALL_STUDIES_PATH = Path('../../../resources/Antares_Simulator_Tests')
To avoid multiple definition (x3 here), I suggest a small refactor : create a config file called e.g `config.yaml` containing this path, and import it here and wherever `ALL_STUDIES_PATH` is required.

2021-04-07 06:15 UTC, jmkerloch commented on src/distrib/win32/sourcefiles.inc.nsh
> -
Test studies were not included in installer. The directory is removed before installer creation in GitHub actions NSIS Installer creation step  : 

`rm -rf src/tests/resources/Antares_Simulator_Tests`

2021-04-14 12:45 UTC, guilpier-code requested changes

2021-04-14 12:45 UTC, guilpier-code commented on .gitmodules
>  [submodule "src/antares-deps"]
Why do we keep : **[submodule "src/antares-deps"]** ?

2021-04-14 12:45 UTC, guilpier-code commented on .gitmodules
>  [submodule "src/tests/resources/Antares_Simulator_Tests"]
Same question as above.

2021-05-03 13:41 UTC, jmkerloch commented on .gitmodules
>  [submodule "src/antares-deps"]
name changed

2021-05-03 13:41 UTC, jmkerloch commented on .gitmodules
>  [submodule "src/tests/resources/Antares_Simulator_Tests"]
name changed

2021-10-11 10:01 UTC, flomnes commented
Fix conficts & merge after #385.

2021-10-21 07:10 UTC, jmkerloch commented
PR too old to merged. Branch is kept for a later integration.

2021-10-21 07:10 UTC, closed without merging