remove Yuni::Math 1
AntaresSimulatorTeam/Antares_Simulator pull request #1980
Opened 2024-03-06 12:32 UTC by payetvin

close #1978

2024-03-06 15:09 UTC, payetvin commented
use `fabs`

2024-03-11 09:32 UTC, flomnes reviewed
- Use `Antares::Utils::isZero` to replace `Yuni::Math::Zero`, with the same threshold
- Check signs (+ or -) with `std::isinf`
- Create `Antares::Utils::Round(double, int)` ?

2024-03-11 09:32 UTC, flomnes commented on src/libs/antares/array/include/antares/array/matrix-to-buffer.hxx
> +        if (v == 0)
Use a custom function here as well, otherwise the behavior changes

```
(1.e-13 == 0) == false
Yuni::Math::Zero(1.e-13) == true
```

2024-03-11 09:32 UTC, flomnes commented on src/libs/antares/correlation/correlation.cpp
> +            if (!isZero(col[y]))
`Antares::Utils::isZero` ?

2024-03-11 09:32 UTC, flomnes commented on src/libs/antares/mersenne-twister/include/antares/mersenne-twister/mersenne-twister.hxx
> +    return (this)->next();
```suggestion
    return this->next();
```

2024-03-11 09:32 UTC, flomnes commented on src/libs/antares/study/parts/thermal/cluster_list.cpp
> +            s->add("volatility.planned", roundToThreeDecimal(c->plannedVolatility));
```suggestion
            s->add("volatility.forced", Antares::Utils::Round(c->forcedVolatility, 3));
        if (!isZero(c->plannedVolatility))
            s->add("volatility.planned", Antares::Utils::Round(c->plannedVolatility,3));
```

2024-03-11 09:32 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
> +            if (std::isinf(ProblemeAResoudre->Xmax[var]))
```suggestion
            if (double xmax = ProblemeAResoudre->Xmax[var]; std::isinf(xmax) && xmax > 0)
```

2024-03-11 09:32 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
> +            if (std::isinf(ProblemeAResoudre->Xmax[var]))
You need to check the sign also

2024-03-11 09:32 UTC, flomnes commented on src/solver/variable/include/antares/solver/variable/storage/stdDeviation.h
> +        auto square = [](double d) { return d >= 0 ? std::sqrt(d) : 0.; };
```suggestion
        auto squareRootChecked = [](double d) { return d >= 0 ? std::sqrt(d) : 0.; };
```

2024-03-11 09:32 UTC, flomnes commented on src/solver/variable/state.cpp
> +                                std::min(static_cast<uint>(
Use `std::clamp` ?

2024-03-11 09:32 UTC, flomnes commented on src/libs/antares/study/parts/thermal/cluster_list.cpp
> +            s->add("startup-cost", roundToThreeDecimal(c->startupCost));
`Antares::Utils::Round(XXX, 3);`

2024-03-11 09:52 UTC, flomnes commented on src/libs/antares/array/include/antares/array/matrix.hxx
> +        return static_cast<T>(trunc(value));
So, `static_cast` from `CString` to `double` is implemented ?

2024-03-11 17:02 UTC, a-zakir approved these changes

2024-03-11 17:07 UTC, flomnes requested changes
1. Other `std::isinf`
2. Still a compilation warning ?

2024-03-13 09:27 UTC, flomnes requested changes
Still many `!= 0` or `== 0`. Please make sure to use `isZero`

2024-03-13 12:18 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
> +                if (std::isinf(Xmin[var]) && Xmin[var] > 0)
```suggestion
                if (std::isinf(Xmin[var]) && Xmin[var] < 0)
```

2024-03-13 12:18 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
>                      ProblemeAResoudre->TypeDeVariable[var] = VARIABLE_BORNEE_SUPERIEUREMENT;
```cpp
const double Xmin = ProblemeAResoudre->Xmin[var];
const double Xmax = ProblemeAResoudre->Xmax[var];
if (...) {

}
```

2024-03-18 08:35 UTC, flomnes commented on src/libs/antares/array/include/antares/array/matrix.hxx
> +                if ((T)column[y] != 0)
isZero

2024-03-18 08:35 UTC, flomnes commented on src/libs/antares/array/include/antares/array/matrix.hxx
> +                if ((T)predicate(column[y]) != 0)
isZero

2024-03-18 08:35 UTC, flomnes commented on src/libs/antares/mersenne-twister/include/antares/mersenne-twister/mersenne-twister.hxx
> +}
Class `MersenneTwister` is not templated, so
1. Place this in a .cpp file
2. Remove keyword `typename`

2024-03-18 08:35 UTC, flomnes commented on src/libs/antares/utils/utils.cpp
> +    return (std::abs(d) < 1.e-6) ? true : false;
use a `constexpr double` for the threshold

2024-03-18 08:43 UTC, flomnes commented on src/libs/antares/utils/utils.cpp
> +    return (std::abs(d) < 1.e-6) ? true : false;
Also, `x ? true : false` is equivalent to `x`.

2024-03-18 12:55 UTC, flomnes reviewed
Minor remarks

2024-03-18 12:55 UTC, flomnes commented on src/libs/antares/utils/utils.cpp
> +    return (std::abs(d) < threshold) ? true : false;
```suggestion
    return std::abs(d) < threshold;
```

2024-03-18 12:55 UTC, flomnes commented on src/libs/antares/mersenne-twister/mersenne-twister.cpp
> +    return this->next();
```suggestion
    return next();
```

2024-03-18 14:23 UTC, flomnes approved these changes

2024-03-18 14:30 UTC, flomnes approved these changes

2024-03-18 14:39 UTC, merged