Add missing parameter to command built by batchrun for OR-Tools
AntaresSimulatorTeam/Antares_Simulator pull request #1984
Opened 2024-03-12 10:12 UTC by flomnes

2024-03-12 17:36 UTC, sylvlecl requested changes

2024-03-12 17:36 UTC, sylvlecl commented on src/tools/batchrun/main.cpp
We should check that ortools solver is not empty, otherwise the command will not be valid

2024-03-13 09:04 UTC, flomnes reviewed
Most changes are due to auto-formatting. I highlighted "real" changes.

2024-03-13 09:04 UTC, flomnes commented on src/tools/batchrun/main.cpp
> +                return EXIT_FAILURE;
Change 1

2024-03-13 09:04 UTC, flomnes commented on src/tools/batchrun/main.cpp
> +                    cmd << " --use-ortools --ortools-solver=" << ortoolsSolver;
Change 2

2024-03-13 09:09 UTC, sylvlecl approved these changes

2024-03-13 11:53 UTC, merged