Feature/change version 8 0 1
AntaresSimulatorTeam/Antares_Simulator pull request #199
Opened 2021-03-04 17:27 UTC by jmkerloch

Changelog to be checked.

2021-03-04 17:46 UTC, flomnes requested changes

2021-03-04 17:46 UTC, flomnes commented on src/CMakeLists.txt
>  set(ANTARES_VERSION_YEAR      2020)
2021

2021-03-04 17:47 UTC, flomnes approved these changes
You can merge if you apply 1 comment

2021-03-08 15:07 UTC, sgatto approved these changes

2021-03-08 15:13 UTC, merged