Remove fetch content
AntaresSimulatorTeam/Antares_Simulator pull request #2036
Opened 2024-04-15 09:03 UTC by JasonMarechal25

2024-04-15 13:34 UTC, flomnes approved these changes

2024-04-15 13:37 UTC, flomnes requested changes
Find an alternative for developers. How many command-lines required to build from scratch ?

2024-04-16 07:57 UTC, JasonMarechal25 commented
> Find an alternative for developers. How many command-lines required to build from scratch ?

We can't do much more. Dependencies need to be installed. Fetch_content is not the way to manage runtime dependencies. CMake is build system, not a package manager, that's a job for vcpkg or conan.

Most dependencies are installed thanks to them being available in apt or vcpkg. Ortools isn't, minizip may be present in vcpkg. We could always provide scripts to install them, but it is generally expected from developers to know how to build and install third partie and from maintainer to disclose dependencies.

2024-04-22 13:56 UTC, flomnes reviewed
We should try to use vcpkg as our dependency manager to ease our work locally & on GH actions

2024-04-22 13:56 UTC, flomnes commented on .github/workflows/windows-vcpkg.yml
> +
Use vcpkg to install minizip-ng ? It is available

2024-04-22 13:56 UTC, flomnes commented on src/packaging/Config.cmake.in
> +find_dependency(ortools)
zlib shenanigans, probably

2024-04-24 08:00 UTC, closed without merging