Add docs for solver-parameters
AntaresSimulatorTeam/Antares_Simulator pull request #2042
Opened 2024-04-18 09:44 UTC by tbittar

2024-04-18 10:36 UTC, pet-mit requested changes

2024-04-18 10:36 UTC, pet-mit commented on docs/user-guide/solver/04-parameters.md
> +- **Default value:** `""`
```suggestion
- **Expected value:** any string
- **Required:** no
- **Default value:** empty string
```

2024-04-18 10:36 UTC, pet-mit commented on docs/user-guide/solver/04-parameters.md
> +  - With SCIP : `solver-parameters = parallel/maxnthreads = 1`
can you add a second parameter in these examples please? (for example MAXNODE for xpress => `THREADS 1 MAXNODE 300000`, and its equivalent in SCIP, or any other parameter)
to allow the users to see the syntax to use to define multiple parameters in this single string (eq in xpress parameters are sperated by an empty space)

2024-04-18 10:40 UTC, pet-mit commented
also, this doesn't render well (see here: https://antares-simulator--2042.org.readthedocs.build/en/2042/user-guide/solver/04-parameters/#solver-parameters)

- for nested lists in mkdocs, you must have 2 extra empty spaces before the `-` of the nested list
- sometimes you have to add an empty space before a list in order for it to render well
- the "The format is solver-specifi..." paragraph should be in the "usage" part

you can test locally by using the `mkdocs serve` command (see here for some tips: https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/doc/optim_update/docs/README.md)

2024-04-18 12:06 UTC, tbittar commented
Yes indeed, I was using the rendering preview of md file from VScode but it is different from the mkdocs page

2024-04-18 15:32 UTC, pet-mit approved these changes

2024-04-22 13:32 UTC, flomnes requested changes
Where is the user supposed to specify these new parameters ?

2024-04-22 13:32 UTC, flomnes commented on docs/user-guide/solver/04-parameters.md
> +      - With SCIP : `solver-parameters = parallel/maxnthreads 1, lp/presolving TRUE`
```suggestion
      - With Xpress : `xpress-parameters = THREADS 1 PRESOLVE 1`
      - With SCIP : `scip-parameters = parallel/maxnthreads 1, lp/presolving TRUE`
```

2024-05-06 16:21 UTC, tbittar commented on docs/user-guide/solver/04-parameters.md
> +      - With SCIP : `solver-parameters = parallel/maxnthreads 1, lp/presolving TRUE`
All parameters within this file relate to `generaldata.ini`, see description at beginning of the file

2024-05-13 07:59 UTC, pet-mit approved these changes

2024-05-14 14:11 UTC, pet-mit commented on docs/user-guide/solver/04-parameters.md
> +      - With SCIP : `solver-parameters = parallel/maxnthreads 1, lp/presolving TRUE`
OK to merge @flomnes ?

2024-05-17 07:49 UTC, tbittar commented
This PR is now useless given the choice that have been made to only set solver parameters from command line, should we close it @pet-mit @flomnes ?

2024-05-17 08:01 UTC, tbittar commented
Instead I opened #2100

2024-05-17 08:06 UTC, closed without merging