Feature/remove license from UI
AntaresSimulatorTeam/Antares_Simulator pull request #211
Opened 2021-03-30 14:24 UTC by guilpier-code

2021-03-30 15:42 UTC, flomnes commented on src/ui/simulator/application/main/main.cpp
> +// EVT_MENU(mnIDHelpContinueOffline, ApplWnd::evtOnHelpContinueOffline)
Remove ?

2021-03-31 11:07 UTC, guilpier-code commented on src/ui/simulator/application/main/main.cpp
> +// EVT_MENU(mnIDHelpContinueOffline, ApplWnd::evtOnHelpContinueOffline)
now corrected

2021-04-01 09:41 UTC, flomnes requested changes
You may remove this declaration

```cpp
    void evtOnShowID(wxCommandEvent&);
```

from **src/ui/simulator/application/main/main.h** since this function is no longer called.

2021-04-01 10:17 UTC, guilpier-code commented
you're right, the correction was brought

2021-04-01 11:39 UTC, flomnes approved these changes

2021-04-01 12:06 UTC, merged