Adequacy patch CSR - revamp output variables
AntaresSimulatorTeam/Antares_Simulator pull request #2306
Opened 2024-08-05 15:22 UTC by flomnes

### Variables
- Remove Spilled CSR
- Add DTG MRG CSR
- Add UNSP. ENRG CSR

### Input parameters
Remove flag "recompute-dtg-mrg"

Make code mode testable by using functions.

TODO
- [ ] Add unit tests

2024-08-05 16:25 UTC, a-zakir commented on src/solver/optimisation/adequacy_patch_csr/post_processing.cpp
> +    if (trigerred)
```suggestion
double recomputeDTG_MRG(bool triggered, double dtgMrg, double ens)
{
    if (triggered)
```

2024-08-26 13:32 UTC, payetvin requested changes
Documentation isn't complete

2024-08-26 13:32 UTC, payetvin commented on .github/workflows/ubuntu.yml
> +  RUN_SIMPLE_TESTS: false
revert

2024-08-26 13:32 UTC, payetvin commented on .github/workflows/windows-vcpkg.yml
> +  RUN_SIMPLE_TESTS: false
revert

2024-09-04 07:56 UTC, payetvin approved these changes

2024-09-04 08:28 UTC, merged