Remove adequacy patch lmr [ANT-1933]
AntaresSimulatorTeam/Antares_Simulator pull request #2341
Opened 2024-08-19 14:49 UTC by payetvin

2024-08-26 13:37 UTC, flomnes reviewed
Remove 
-  `LocalMatching::setToZeroOutsideOutsideLinks`
- `LocalMatching::enabled`

They are no longer used.

Please move the remaining property directly to class `AdequacyPatchParams`, and remove sub-class LocalMatching

Remove exception `AdqPatchDisabledLMR`, it is now dead code.

2024-08-26 13:37 UTC, flomnes commented on src/solver/simulation/include/antares/solver/simulation/economy.h
> +    std::vector<std::unique_ptr<Optimization::WeeklyOptimization>> weeklyOptProblems_;
This `unique_ptr` is no longer necessary.
```suggestion
    std::vector<Optimization::WeeklyOptimization> weeklyOptProblems_;
```

2024-08-26 13:40 UTC, flomnes commented
Local matching is enabled in [this batch](https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/tree/main/adequacy-patch-CSR), please make sure to remove all properties related to LMR from relevant configuration files (generaldata.ini) and publish a new version.

2024-08-29 15:39 UTC, payetvin commented
https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/pull/31

2024-08-30 12:56 UTC, flomnes submitted a review, later dismissed

2024-08-30 12:56 UTC, flomnes commented on src/solver/simulation/economy.cpp
> +            weeklyOptProblems_.push_back(weekOpt);
```suggestion
            weeklyOptProblems_.emplace_back(options, /* other args */);
```
See https://en.cppreference.com/w/cpp/container/vector/emplace_back

2024-08-30 13:00 UTC, flomnes requested changes
Please remove `AdequacyPatchRuntimeData::AdequacyFirstStep`, and fix function `setBoundsForUnsuppliedEnergy` (possible regression)

2024-09-02 09:08 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
>              // adq patch: update ENS <= DENS in 2nd run
Please remove l.136 - l. 143

2024-09-02 09:21 UTC, flomnes requested changes
Please update the migration guide & changelog (removed options)

2024-09-02 12:55 UTC, flomnes approved these changes

2024-09-03 14:56 UTC, flomnes approved these changes

2024-09-03 14:56 UTC, merged