Remove manually allocated memory
AntaresSimulatorTeam/Antares_Simulator pull request #2363
Opened 2024-08-28 10:54 UTC by payetvin

#2244

2024-08-29 12:48 UTC, flomnes commented on src/libs/antares/study/area/list.cpp
> +            ret = area.hydro.series->loadGenerationTS(area.id, buffer, studyVersion) && ret;
No need to remove the alias, you could still have
```cpp
auto* hydroSeries = area.hydro.series.get();
// ...
ret = hydroSeries->loadGenerationTS(/* ... */);
```

2024-08-29 12:48 UTC, flomnes commented on src/libs/antares/study/study.cpp
>  }
You probably no longer need these functions. Memory will be released when `Study` will be released, probably just a little later than now.

The only possible change of behaviour I foresee is if `prepro` objects are re-used, in which case we want to reset them beforehand.

After looking at the code, it's exactly what happens, because of TS refresh. Since this feature is to be removed "soon", please just add a comment to remind us that these functions (and probably more...) should be removed when removing TS refresh.

2024-08-29 12:48 UTC, flomnes commented on src/solver/ts-generator/include/antares/solver/ts-generator/xcast/studydata.h
> +    std::array<Matrix<float>, 12> correlation;
You lost a `const` qualifier here, the equivalent might be
```cpp
std::array<const Matrix<float>, 12> correlation;
```

2024-08-29 12:48 UTC, flomnes commented on src/solver/ts-generator/xcast/studydata.cpp
> +            auto m = Matrix<float>();
```suggestion
            Matrix<float> m;
```

2024-08-29 12:48 UTC, flomnes commented on src/solver/ts-generator/xcast/studydata.cpp
>                  correlation[realmonth] = m;
```suggestion
                correlation[realmonth] = Matrix<float>();
```

2024-08-29 12:56 UTC, payetvin commented on src/libs/antares/study/area/list.cpp
> +            ret = area.hydro.series->loadGenerationTS(area.id, buffer, studyVersion) && ret;
The alias is used only once and the length is not a lot different, useless imo

2024-08-29 13:09 UTC, payetvin commented on src/solver/ts-generator/include/antares/solver/ts-generator/xcast/studydata.h
> +    std::array<Matrix<float>, 12> correlation;
using const here doesn't makes a lot of sense, those matrix will be modified

2024-08-29 14:15 UTC, flomnes requested changes
Please revert **include/antares/solver/variable** and open a new PR

2024-08-30 07:39 UTC, flomnes approved these changes

2024-08-30 07:40 UTC, merged