Replace AddNode with SumNode
AntaresSimulatorTeam/Antares_Simulator pull request #2396
Opened 2024-09-13 08:14 UTC by pet-mit

In expressions, replace "AddNode" that takes only 2 operands, with "SumNode" that takes 0 to N operands.
This will allow shallower trees.

2024-09-13 09:53 UTC, a-zakir commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    }
```suggestion
    SumNode();

    /**
     * @brief Constructs a sum node with the specified operands.
     *
     * @param operands The list of operands
     */
    template<typename... NodePtr>
    explicit SumNode(NodePtr... operands)
    {
        
        if constexpr (sizeof...(NodePtr) != 0) {
           operands_ = createVector((Node*)operands...);
        }
    }
```

2024-09-13 09:54 UTC, a-zakir commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    std::vector<Node*> operands_;
```suggestion
    std::vector<Node*> operands_={};
```

2024-09-13 12:36 UTC, a-zakir commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    uint getSize() const;
```suggestion
    unsigned int getSize() const;
```

2024-09-13 12:37 UTC, a-zakir commented on src/solver/expressions/nodes/SumNode.cpp
> +uint SumNode::getSize() const
```suggestion
unsigned int SumNode::getSize() const
```

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    std::vector<Node*> getOperands() const;
Don't force a copy
```suggestion
    const std::vector<Node*>& getOperands() const;
    Node* operator[](std::size_t idx) const;
```

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/iterators/pre-order.cpp
> +    }
👍🏻

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/nodes/SumNode.cpp
> +unsigned int SumNode::getSize() const
```suggestion
unsigned int SumNode::size() const
```

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/visitors/CompareVisitor.cpp
> +        for (uint i = 0; i < node->getSize(); ++i)
```suggestion
        for (std::size_t i = 0; i < node->size(); ++i)
```

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/visitors/LinearityVisitor.cpp
> +                           LinearStatus::CONSTANT,
Is this a neutral element for + ?
LinearStatus::CONSTANT + x = x for all x

Add tests

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/visitors/PrintVisitor.cpp
> +    return std::accumulate(std::begin(operands) + 1,
```suggestion
    return std::accumulate(std::next(std::begin(operands)),
```

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    explicit SumNode(NodePtr... operands)
You need to use thr `requires` keyword here if you want to use concept `NodePtr`. Currently it's just a template parameter name.

https://en.cppreference.com/w/cpp/language/constraints

2024-09-13 13:19 UTC, flomnes commented on src/solver/expressions/visitors/CloneVisitor.cpp
> +    return registry_.create<Nodes::SumNode>(clonedOperands);
You may avoid a copy with a `std::move` here, if SumNode had move constructor. 

In `SumNode`
```cpp
SumNode(std::vector<Node*>&& operands) : operands_(std::move(operands)) {}
```
Here
```cpp
// Give ownership of clonedOperands to the caller
return registry_.create<Nodes::SumNode>(std::move(clonedOperands));
```

2024-09-13 13:38 UTC, pet-mit commented on src/solver/expressions/visitors/LinearityVisitor.cpp
> +                           LinearStatus::CONSTANT,
yes it is (cf. test "linear_status_plus" in test_LinearVisitor)

2024-09-13 13:39 UTC, pet-mit commented on src/solver/expressions/visitors/LinearityVisitor.cpp
> +                           LinearStatus::CONSTANT,
what tests would you like me to add?

2024-09-13 13:45 UTC, flomnes commented on src/solver/expressions/visitors/LinearityVisitor.cpp
> +                           LinearStatus::CONSTANT,
SumNode(new LiteralNode, new LiteralNode)) => CONSTANT
SumNode(new MultiplyNode(VariableNode, VariableNode)) => NON_LINEAR
etc.

2024-09-16 09:00 UTC, pet-mit commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    explicit SumNode(NodePtr... operands)
I'm not sure I understand how this should be used. Where should i use it?

2024-09-16 09:33 UTC, flomnes requested changes
Pending issues
- Memory leaks related to the usage of `new` in the tests
- Wrongful usage of a concept (you need to use `requires`)

2024-09-16 09:33 UTC, flomnes commented on src/tests/src/solver/expressions/test_LinearVisitor.cpp
> +                           new MultiplicationNode(new VariableNode("x"), new VariableNode("y")));
Plenty of memory leaks here, could you replace
```cpp
new Node(args...)
```
with
```cpp
create<Node>(args...)
```
?

2024-09-16 09:43 UTC, flomnes commented on src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
> +    explicit SumNode(NodePtr... operands)
Something like
```cpp
#include <concepts>
#include <numeric>
#include <string>

template<typename FirstArg, typename... Args>
requires(std::convertible_to<Args, FirstArg> && ...)
FirstArg sum(FirstArg first, Args... args)
{
    return first;
}

int main()
{
    sum(1);                       // OK
    sum(1, 2);                    // OK 2 is convertible to int
    sum(2, std::string("DD"));    // KO std::string is not convertible to int
    sum(1, 2, std::string("DD")); // KO std::string is not convertible to int
}
```
But then you'd need a 0 argument version : the default constructor. You can let the compiler define it.

2024-09-16 12:19 UTC, flomnes approved these changes

2024-09-16 12:19 UTC, merged