Parse yaml
AntaresSimulatorTeam/Antares_Simulator pull request #2433
Opened 2024-09-27 08:08 UTC by JasonMarechal25

2024-09-27 09:04 UTC, flomnes requested changes
You could polish error-handling `node.as<XXX>` can throw exceptions, these exceptions are not caught currently.

Also, you should add tests for error-handling (provide an invalid YAML, check for errors)

2024-09-27 09:04 UTC, flomnes commented on src/tests/src/solver/modelParser/testModelParser.cpp
> +    BOOST_CHECK(libraryObj.models[0].constraints.size() == 0);
```suggestion
    auto& model = libraryObj.models[0];
    BOOST_CHECK(model.parameters.empty());
    BOOST_CHECK(model.variables.empty());
    BOOST_CHECK(model.ports.empty());
    BOOST_CHECK(model.port_field_definitions.empty());
    BOOST_CHECK(model.constraints.empty());
```

2024-09-27 09:04 UTC, flomnes commented on src/tests/src/solver/modelParser/testModelParser.cpp
> +    BOOST_CHECK(libraryObj.models[0].description == "model_description");
Use `BOOST_REQUIRE` to exit in case of invalid size (avoid subsequent segfault)

```suggestion
    BOOST_REQUIRE_EQUAL(libraryObj.models.size(), 1);
    BOOST_CHECK_EQUAL(libraryObj.models[0].id, "model_id");
    BOOST_CHECK_EQUAL(libraryObj.models[0].description, "model_description");
```

2024-09-27 09:04 UTC, flomnes commented on src/tests/src/solver/modelParser/testModelParser.cpp
> +    auto library = R"(
```suggestion
    const std::string library = R"(
```

2024-09-27 09:04 UTC, flomnes commented on src/solver/modelParser/encoders.hxx
> +        rhs.id = node["id"].as<std::string>();
if(!node.IsMap()) return false;

2024-09-27 11:49 UTC, flomnes commented on src/tests/src/solver/modelParser/testModelParser.cpp
You only test vectors of size 0 or 1. You should go up to 2

2024-09-29 15:30 UTC, a-zakir commented
Nice job!
Here some minor remarks :
Are the encode methods mandatory ? If not are we going to use them?
Even though using structs is the most straightforward way to read the yaml, have you considered basic class with member data private, maybe making friends the decode methods?

2024-09-30 08:10 UTC, JasonMarechal25 commented on src/tests/src/solver/modelParser/testModelParser.cpp
New tests added

2024-10-01 16:07 UTC, flomnes approved these changes

2024-10-01 16:07 UTC, merged