Modeler 1.1c: Scenarize problem filler [ANT-2003]
AntaresSimulatorTeam/Antares_Simulator pull request #2445
Opened 2024-09-30 14:24 UTC by payetvin

2024-10-04 09:00 UTC, pet-mit requested changes

2024-10-04 09:00 UTC, pet-mit commented on src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemFiller.h
> +    std::vector<unsigned> scenariosSelected;
I don't think these should be public. only allow read in public

2024-10-07 15:49 UTC, flomnes commented on src/tests/src/solver/modeler/api/testModelerLPbuilder.cpp
> +    auto var1 = pb->getVariable("0-0");
Please use a clearer naming here
```suggestion
    auto var1 = pb->getVariable("variable-ts0-sc0");
```

2024-10-09 13:34 UTC, flomnes approved these changes

2024-10-10 08:33 UTC, pet-mit approved these changes

2024-10-10 08:47 UTC, merged