Remove timeseries refresh
AntaresSimulatorTeam/Antares_Simulator pull request #2451
Opened 2024-10-04 13:30 UTC by payetvin

Remove the refresh feature: no known users, add unnecessary complexity to the code

2025-05-22 13:34 UTC, JasonMarechal25 requested changes
Only missing documentation update for refresh

2025-06-05 13:56 UTC, flomnes requested changes
LGTM
We should exit with an error if key `refreshtimeseries` is not empty (change of behavior)

2025-06-11 11:19 UTC, flomnes commented on src/solver/simulation/include/antares/solver/simulation/solver.hxx
> +        // It will export the time-series into the output in the same time
Consider a function rename for more expressiveness
```suggestion
        // It will export the time-series into the output at the same time
```

2025-06-16 09:21 UTC, JasonMarechal25 approved these changes

2025-06-17 08:41 UTC, flomnes approved these changes

2025-06-17 08:42 UTC, merged