Renewable output
AntaresSimulatorTeam/Antares_Simulator pull request #250
Opened 2021-05-10 16:17 UTC by flomnes

Write renewable input data into the `output` directory 
* year by year
* synthesis
* record years

For each time granularity
* hourly
* daily
* weekly
* monthly
* annual

2021-05-26 12:43 UTC, guilpier-code requested changes

2021-05-26 12:43 UTC, guilpier-code commented on src/solver/variable/area.inc.hxx
> +            state.yearEndReset();
**yearEndReset** has already been called for thermal clusters. Calling it here again could set to zero some results computed for thermal clusters.

2021-05-26 12:43 UTC, guilpier-code commented on src/solver/variable/area.inc.hxx
>              // Variables
**yearEndBuildFromThermalClusterIndex** function name is very unclear on what the function really does.
This name should be changed, even if it has nothing to see with the current PR.

2021-05-26 12:43 UTC, guilpier-code commented on src/solver/variable/commons/links/links.hxx.inc.hxx
> +inline void Links::yearEndBuildPrepareDataForEachRenewableCluster(State& state,
This function is useless for now, but might be used someday (to be checked).

2021-06-01 09:07 UTC, flomnes commented on src/solver/variable/commons/links/links.hxx.inc.hxx
> +inline void Links::yearEndBuildPrepareDataForEachRenewableCluster(State& state,
This function is used to recover hourly data for renewable clusters, see **src/solver/variable/economy/renewableGeneration.h:290**.
```cpp
void yearEndBuildPrepareDataForEachRenewableCluster(State& state,
                                                    uint year,
                                                    unsigned int numSpace)
{
    for (unsigned int i = 0; i <= state.study.runtime->rangeLimits.hour[Data::rangeEnd]; ++i)
    {
        state.renewableClusterProductionForYear[i]
          += pValuesForTheCurrentYear[numSpace][state.renewableCluster->areaWideIndex].hour[i];
    }
 // Next variable
    NextType::yearEndBuildPrepareDataForEachRenewableCluster(state, year, numSpace);
}
```

2021-06-01 09:14 UTC, flomnes commented on src/solver/variable/area.inc.hxx
>              // Variables
How about **yearEndRecoverThermalData** ?

2021-06-01 09:43 UTC, flomnes commented on src/solver/variable/area.inc.hxx
> +            state.yearEndReset();
I duplicated this function into two : one for thermal data, one for renewable data. See commit 9573759.

2021-06-11 11:28 UTC, flomnes commented
Local merge in PR #267

2021-06-11 11:28 UTC, closed without merging