Fix/centos build (#2509)
AntaresSimulatorTeam/Antares_Simulator pull request #2510
Opened 2024-11-28 13:06 UTC by a-zakir

2024-11-28 15:24 UTC, flomnes reviewed
For ccache, it requires updating the online cache for persistency between runs.

2024-11-28 15:24 UTC, flomnes commented on .github/workflows/centos7.yml
> +          gh --version
On the ubuntu runners, gh is installed by default
```suggestion
```

2024-12-04 09:41 UTC, payetvin requested changes

2024-12-04 09:41 UTC, payetvin commented on .github/workflows/centos7.yml
> +      - fix/centos-build
remove this

2024-12-04 09:43 UTC, a-zakir commented on .github/workflows/centos7.yml
> +      - fix/centos-build
done

2024-12-04 09:56 UTC, payetvin approved these changes

2024-12-04 10:15 UTC, merged