Branch 8.8: Use vcpkg
AntaresSimulatorTeam/Antares_Simulator pull request #2549
Opened 2024-12-26 10:42 UTC by payetvin

2025-01-03 13:11 UTC, a-zakir commented on .github/workflows/install-cmake-328/action.yml
> +name: "Install cmake 3.28 using devtoolset 10 if possible"
where this workflow is used?
cmake 3.28 can be installed with pip

2025-01-03 13:20 UTC, a-zakir commented on src/CMakeLists.txt
> +	message (FATAL_ERROR "Sirius solver not found. Sirius solver can be compiled with -DBUILD_sirius=ON or you can specify previous dependency install directory with -DCMAKE_PREFIX_PAT ")
is it true that BUILD_sirius=ON will build Sirius?

2025-01-03 13:20 UTC, a-zakir commented on src/CMakeLists.txt
> +	message (FATAL_ERROR "Sirius solver not found. Sirius solver can be compiled with -DBUILD_sirius=ON or you can specify previous dependency install directory with -DCMAKE_PREFIX_PAT ")
i don't think so

2025-01-06 12:33 UTC, flomnes requested changes

2025-01-06 12:33 UTC, flomnes commented on src/CMakeLists.txt
> +	message (FATAL_ERROR "Sirius solver not found. Sirius solver can be compiled with -DBUILD_sirius=ON or you can specify previous dependency install directory with -DCMAKE_PREFIX_PAT ")
```suggestion
	message (FATAL_ERROR "Sirius solver not found. Sirius solver can be compiled with -DBUILD_sirius=ON or you can specify a dependency install directory with -DCMAKE_PREFIX_PATH")
```

2025-01-06 13:25 UTC, flomnes approved these changes

2025-01-06 13:39 UTC, merged