UI - clusters time series : extracting common code from cluster TS classes
AntaresSimulatorTeam/Antares_Simulator pull request #340
Opened 2021-08-12 10:04 UTC by guilpier-code

2021-08-16 13:56 UTC, flomnes requested changes
There is no need to differentiate data structures by thermal / renewable (l. 375 and after). We only use a common member `series`.

2021-08-16 15:40 UTC, guilpier-code commented
> 
> 
> There is no need to differentiate data structures by thermal / renewable (l. 375 and after). We only use a common member `series`.
Actually, it was not made on purpose :

2021-08-17 08:46 UTC, flomnes commented
> > There is no need to differentiate data structures by thermal / renewable (l. 375 and after). We only use a common member `series`.
> 
> Actually, it was not made on purpose : if you change
> `internalThermalClusterChanged(Antares::Data::ThermalCluster* cluster)`
> into :
> `internalClusterChanged(Antares::Data::Cluster* cluster)`
> and make that method common, you have to deal with the **notifier** (and the event **onClusterChanged**) in the classes constructor.
> As changing **onClusterChanged** has consequances in many places, I think we should wait until other part of the code is factorized.

OK

2021-08-17 08:46 UTC, flomnes approved these changes

2021-08-17 08:46 UTC, merged