TS number tests with embedded study
AntaresSimulatorTeam/Antares_Simulator pull request #399
Opened 2021-10-04 18:01 UTC by guilpier-code

2021-10-06 12:32 UTC, flomnes reviewed
I mostly agree with this way to do things.

Add intermodal_ko tests ?

2021-10-06 12:32 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +}
If the thermal cluster is "must-run", it should be added to mustRunList instead

2021-10-06 12:32 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +}
~~l. 50 : `area->thermal.clusters` is of type `std::map<string, std::shared_ptr<ThermalCluster>>`. Therefore there is no need to call `get()` to access the raw pointer.~~

~~Doing so may lead to a double free (happened in the past).~~

I was wrong.

2021-10-06 12:32 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +BOOST_AUTO_TEST_CASE(two_areas_3_thermal_clusters_with_different_number_of_ready_made_ts___check_intra_modal_ok)
Should be **ko**

2021-10-06 15:18 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +}
Check that the TS numbers satisfy the intra-modal rule here.

2021-10-06 15:18 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +{
KO

2021-10-07 11:44 UTC, guilpier-code commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +}
done

2021-10-07 11:44 UTC, guilpier-code commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +{
done

2021-10-11 15:23 UTC, flomnes requested changes

2021-10-11 15:23 UTC, flomnes commented on src/tests/src/solver/simulation/CMakeLists.txt
> +)
Why create a lib ? We could just add `libantares-core` and `libmodel_antares` after line 41 instead.

2021-10-11 15:23 UTC, flomnes commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	BOOST_TEST((thermalTsNumber>= 0 && thermalTsNumber < thermalNumberOfTs));
Remove useless parentheses.

2021-10-13 08:29 UTC, flomnes commented on src/solver/simulation/timeseries-numbers.cpp
> +void addInterModalTimeSeriesToMessage(const bool* isTSintermodal, std::string & interModalTsMsg)
`std::array<bool, size>`

2021-10-13 13:23 UTC, flomnes commented on src/solver/simulation/timeseries-numbers.cpp
>           0 != (Data::timeSeriesWind & parameters.timeSeriesToRefresh),
Use `std::array` for `nbTimeseriesByMode`, `intramodal_draws` and `isTSgenerated` as well ?

2021-10-13 13:56 UTC, guilpier-code commented on src/tests/src/solver/simulation/CMakeLists.txt
> +)
I wanted to separate sources from code and tests sources. 
Maybe not relevant.
Changes were done here.

2021-10-13 13:56 UTC, guilpier-code commented on src/tests/src/solver/simulation/tests-ts-numbers.cpp
> +	BOOST_TEST((thermalTsNumber>= 0 && thermalTsNumber < thermalNumberOfTs));
done

2021-10-13 14:25 UTC, guilpier-code commented on src/solver/simulation/timeseries-numbers.cpp
> +void addInterModalTimeSeriesToMessage(const bool* isTSintermodal, std::string & interModalTsMsg)
done

2021-10-13 14:25 UTC, guilpier-code commented on src/solver/simulation/timeseries-numbers.cpp
>           0 != (Data::timeSeriesWind & parameters.timeSeriesToRefresh),
done

2021-10-22 09:48 UTC, merged