Name constraints + binding constraints
AntaresSimulatorTeam/Antares_Simulator pull request #417
Opened 2021-10-18 16:01 UTC by flomnes

Add a name for some constraints (not all).

2021-10-26 08:26 UTC, flomnes reviewed
Add .md on how constraints are named

2021-10-26 08:26 UTC, flomnes commented on src/solver/utils/named_problem.h
> +  const std::vector<std::string> NomDesContraintes;
Add consistency check functions `this->NombreDeVariables == NomDesVariables.size()`

2021-10-26 08:26 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +                      problemeAResoudre->NombreDeVariables,
Do not provide an empty `std::vector`

2021-10-26 08:35 UTC, flomnes reviewed
Performance ?

2021-10-26 08:35 UTC, flomnes commented on src/solver/utils/named_problem.h
> +                 const std::vector<std::string>& NomDesContraintes) : NomDesVariables(NomDesVariables), NomDesContraintes(NomDesContraintes) {}
`Copy of a std::vector<std::string>`. Is it necessary or can we just keep a reference ?

2021-10-26 08:35 UTC, flomnes commented on src/solver/simulation/sim_structure_probleme_economique.h
> +    Antares::Data::ConstraintName NomDeLaContrainteCouplante;
`const char*` ? We add a dependency here

2021-10-26 08:38 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +    PROBLEME_NOMME Probleme(ProblemeAResoudre->NomDesVariables,
`PROBLEME_SIMPLEXE_NOMME`

2021-10-26 14:47 UTC, guilpier-code requested changes

2021-10-26 14:47 UTC, guilpier-code commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> +            NomDeLaContrainte
ts = timeStepInYear, right ?
If so, please change its name to something more explicit

2021-10-26 14:47 UTC, guilpier-code commented on src/solver/simulation/sim_structure_probleme_economique.h
> +    Antares::Data::ConstraintName NomDeLaContrainteCouplante;
Indeed, why not define a string here (instead of a **ConstraintName**) ? (and remove the dependency)
No trouble to change this apparently

2021-10-26 14:47 UTC, guilpier-code commented on src/solver/utils/ortools_wrapper.h
>  #ifndef __ORTOOLS_WRAPPER__
This file is not in the IDE solution generated by cmake. It will not be searched in case of search over the entire solution.
Same thing for **ortools_utils.h**

2021-10-26 14:47 UTC, guilpier-code commented on src/libs/antares/study/runtime/runtime.h
> +    ConstraintName name;
why not a string ?

2021-10-26 14:47 UTC, guilpier-code commented on src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
> +        ProblemeAResoudre->NomDesVariables.clear();
Is it really useful (to deallocate vectors manually) ?

2021-10-26 19:24 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +    PROBLEME_NOMME Probleme(ProblemeAResoudre->NomDesVariables,
Done

2021-10-26 19:24 UTC, flomnes commented on src/solver/simulation/sim_structure_probleme_economique.h
> +    Antares::Data::ConstraintName NomDeLaContrainteCouplante;
I'll use `const char*` to keep this structure in a "C-style"

2021-10-26 19:24 UTC, flomnes commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> +            NomDeLaContrainte
```cpp
int ts = study.runtime->weekInTheYear[numSpace] * 168 + Pdt;
```

Right, name must be changed.

2021-10-26 19:24 UTC, flomnes commented on src/solver/utils/named_problem.h
> +  const std::vector<std::string> NomDesContraintes;
done

2021-10-26 19:24 UTC, flomnes commented on src/solver/utils/ortools_wrapper.h
>  #ifndef __ORTOOLS_WRAPPER__
ok

2021-10-26 19:24 UTC, flomnes commented on src/solver/utils/named_problem.h
> +                 const std::vector<std::string>& NomDesContraintes) : NomDesVariables(NomDesVariables), NomDesContraintes(NomDesContraintes) {}
const ref

2021-10-26 19:24 UTC, flomnes commented on src/libs/antares/study/runtime/runtime.h
> +    ConstraintName name;
I'll be using a `const char*`

2021-10-26 19:27 UTC, flomnes commented on src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
> +        ProblemeAResoudre->NomDesVariables.clear();
No, the underlying memory should be deallocated when `~std::vector<T>` is called. This code implies meaning but can be safely removed.

2021-10-26 19:49 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +        }
Use temporary for variable name => one single call to MakeNumVar

2021-11-02 14:29 UTC, flomnes commented on src/libs/antares/study/runtime/runtime.h
> +    ConstraintName name;
I'll be using a `std::string`. Using `const char*` would force us to manage memory (deep copies are needed).

2021-11-09 10:36 UTC, flomnes commented
Contained in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/431

2021-11-09 10:36 UTC, closed without merging