Add infeasibility analysis tool
AntaresSimulatorTeam/Antares_Simulator pull request #427
Opened 2021-10-22 14:04 UTC by flomnes

2021-10-22 14:08 UTC, flomnes commented on src/solver/infeasible-diag/problem.cpp
> +    assert(mSlackVariables.size() > 0);
Absence of slack variables shouldn't be fatal : we only provide a analysis

2021-10-26 08:58 UTC, flomnes reviewed
Check slack variables

2021-10-26 08:58 UTC, flomnes commented on src/solver/cmake/infeasible-diag.cmake
> +add_library(libinfeasible_diag ${SRC_INFEASIBLE_DIAG})
Find a better name ?

2021-10-27 07:03 UTC, guilpier-code requested changes

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemDiag diag(&Probleme, "(.)*");
we discussed it : **diagnostic** is not a good name for our analysis. Diag is worse.
Whatever name we choose, it should appear in full (not diag for diagnostic, and certainly not the short name for analysis)

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemDiag diag(&Probleme, "(.)*");
Smothing else on this line : regular expression pattern should be an inner of **InfeasibleProblemDiag**

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/infeasible-diag/problem.cpp
> +          "Cannot generate infeasibility report: no constraints have been pre-selected");
For me, this message is unclear.
with the good regex pattern, is this possible that no slack variable was built ?
And what would it mean ?

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/infeasible-diag/problem.cpp
> +          "Cannot generate infeasibility report: linear problem could not be solved");
Would not this be more clear : "linear problem could not be solved, and infeasibility analysis could not help"

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/infeasible-diag/report.cpp
> +    std::sort(std::begin(mConstraints), std::end(mConstraints), compareSlackSolutions);
Maybe missing some introductory message : "Infeasibility analysis gives following results :"

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/infeasible-diag/report.cpp
> +void InfeasibleProblemReport::printLargest(unsigned int n)
**printLargest** : why not make this function's parameter a **InfeasibleProblemReport** member or constant ?
And in that case, we could call this method **print**

2021-10-27 07:03 UTC, guilpier-code commented on src/solver/cmake/infeasible-diag.cmake
> +set(SRC_INFEASIBLE_DIAG
Of course, if we change infeasible into something else, like analysis for instance, we should also change the name of the directory containing these files

2021-10-27 11:56 UTC, flomnes commented on src/solver/infeasible-diag/problem.cpp
> +          "Cannot generate infeasibility report: no constraints have been pre-selected");
With the right regex, we will match at least 1 constraint (hydro levels for example), even if the user has not defined any binding constraints.

This check is added for extra safety

2021-10-27 11:56 UTC, flomnes commented on src/solver/infeasible-diag/report.cpp
> +void InfeasibleProblemReport::printLargest(unsigned int n)
I don't understand this remark, can you elaborate ?

2021-10-27 11:56 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemDiag diag(&Probleme, "(.)*");
Name: I agree and will rename this class to **InfeasibleProblemAnalysis**.

I don't understand the 2nd remark.

2021-10-27 11:56 UTC, flomnes commented on src/solver/infeasible-diag/report.cpp
> +    std::sort(std::begin(mConstraints), std::end(mConstraints), compareSlackSolutions);
done

2021-10-27 11:56 UTC, flomnes commented on src/solver/cmake/infeasible-diag.cmake
> +set(SRC_INFEASIBLE_DIAG
ok

2021-10-27 12:20 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemDiag diag(&Probleme, "(.)*");
Sorry, let me be more clear : you pass the regex pattern **"(.)*"** to the constructor of **InfeasibleProblemAnalysis**.
This pattern should be a data of the class, and not be passed to this constructor, whatever this pattern is.

2021-10-27 12:28 UTC, guilpier-code commented on src/solver/infeasible-diag/report.cpp
> +void InfeasibleProblemReport::printLargest(unsigned int n)
Sure : somewhere else in the code, you call : 
`printLargest(10);`
but the **n** (that is **10** here) that you pass, should it not be a inner data of the class **InfeasibleProblemReport** ?
I mean  : does the caller of **printLargest** have to known  that the function prints up to 10 incorrect constraints ?
And if you make this **n** an inner data, **printLargest** should be renamed **print()**

2021-10-27 12:40 UTC, guilpier-code commented on src/solver/infeasible-diag/problem.cpp
> +          "Cannot generate infeasibility report: no constraints have been pre-selected");
ok, that said, user will probably not know what is a **pre-selected** constraint.
So the message will be obscure to him.
Maybe the message could be : "Cannot generate infeasibility report: no incorrect constraint found"

2021-10-27 13:04 UTC, flomnes commented on src/solver/infeasible-diag/report.cpp
> +void InfeasibleProblemReport::printLargest(unsigned int n)
OK, understood & accepted

2021-10-27 13:05 UTC, flomnes commented on src/solver/infeasible-diag/problem.cpp
> +          "Cannot generate infeasibility report: no constraints have been pre-selected");
I suggest: "no constraint have been selected". The message you suggest is misleading, it implies that the problem is feasible, even if it isn't.

2021-10-27 13:06 UTC, flomnes commented on src/solver/cmake/infeasible-diag.cmake
> +add_library(libinfeasible_diag ${SRC_INFEASIBLE_DIAG})
done

2021-11-02 16:05 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemDiag diag(&Probleme, "(.)*");
Why not provide it to the constructor ?

2021-11-09 10:36 UTC, flomnes commented
Contained in https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/431

2021-11-09 10:36 UTC, closed without merging