Infeasible problem analysis: pretty print
AntaresSimulatorTeam/Antares_Simulator pull request #431
Opened 2021-10-27 16:14 UTC by flomnes

2021-11-04 09:01 UTC, flomnes reviewed
Display which parameter could be wrong

2021-11-04 09:01 UTC, flomnes commented on src/solver/infeasible-problem-analysis/problem.cpp
> +                mSlackVariables.push_back(slack);
Careful with `push_pack`. Use `std::vector<>::reserve` ?

2021-11-04 12:59 UTC, guilpier-code requested changes

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemAnalysis analysis(&Probleme, ".+::.+");
the regex pattern **".+::.+"** should be an internal data of **InfeasibleProblemAnalysis**, and so should not be passed to its constructor.
Clients of **InfeasibleProblemAnalysis** should not have to know about this regex pattern.

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +            report = analysis.produceReport(10);
same thing as above : **10** should be an internal data of **InfeasibleProblemReport** and should not be passed to **produceReport** as argument, neither should it be passed to the constructor of **InfeasibleProblemReport**.
Clients of **InfeasibleProblemReport** should not have to know that the 10 first problematic constraints are spotted and raised to the user.

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        report.prettyPrint();
Should not we have, instead : 
```
        Optimization::InfeasibleProblemAnalysis analysis(&Probleme, ".+::.+");
        try
        {
            Optimization::InfeasibleProblemReport  report = analysis.produceReport(10);
            report.prettyPrint();
        }
        catch (const Optimization::SlackVariablesEmptyr& ex)
        {
            logs.error() << ex.what();
        }
        ....
```

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/problem.cpp
> +    InfeasibleProblemReport r;
**r** should be renamed into **report**

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/problem.cpp
> +    const MPSolver::ResultStatus s = Solve();
**s** (status) should be renamed into something more expressive

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/problem.cpp
> +    }
Appending slack variables to report should be done in the report constructor, so we should pass **mSlackVariables** to it.

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/report.cpp
> +void InfeasibleProblemReport::rawPrint() const
**rawPrint** does not seem to be called. If so, we should remove it.

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/problem.cpp
> +    r.trimTo(nbSlackVariablesInReport);
Does the analysis problem have to know that report trims slack variables ?
I recommend to make  **trimTo** a private method of the report and call it in its **prettyPrint** function.

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/report.h
> +    void prettyPrint();
For me, only the report **constructor** and the **prettyPrint** method should be public. The other functions should be private. **append** should called in the constructor, **rawPrint** seems to be never called,  **trimTo** should be called in **prettyPrint**.

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/report.cpp
> +    mConstraints.resize(n);
Could possibly be : 
```
 mConstraints.resize(n > mConstraints.size() ? mConstraints.size() : n);
```

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/report.cpp
> +void InfeasibleProblemReport::prettyPrint()
**prettyPrint** is a bit long, couldn't it be split into 2 parts (2 private methods calls) ? for instance : 
- **countTypes** updating 
- logging possible causes of infeasibility

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> +        int tsInYear = study->runtime->weekInTheYear[numSpace] * 168 + Pdt;
For me **timeStepInYear** is better

2021-11-04 12:59 UTC, guilpier-code commented on src/solver/utils/ortools_utils.cpp
> +        const MPVariable* x;
**x** should be renamed into **var** for instance

2021-11-04 14:05 UTC, flomnes commented on src/solver/utils/ortools_utils.cpp
> +          constraintName = NomDesContraintes[idxRow];
use curly braces here

2021-11-05 10:36 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        report.prettyPrint();
ok

2021-11-05 10:36 UTC, flomnes commented on src/solver/infeasible-problem-analysis/problem.cpp
> +    InfeasibleProblemReport r;
ok

2021-11-05 10:37 UTC, flomnes commented on src/solver/infeasible-problem-analysis/problem.cpp
> +    const MPSolver::ResultStatus s = Solve();
ok

2021-11-05 10:37 UTC, flomnes commented on src/solver/infeasible-problem-analysis/report.h
> +    void prettyPrint();
ok

2021-11-05 10:37 UTC, flomnes commented on src/solver/infeasible-problem-analysis/report.cpp
> +    mConstraints.resize(n);
I won't use a ternary, but change this. See code

2021-11-05 10:38 UTC, flomnes commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
> +        int tsInYear = study->runtime->weekInTheYear[numSpace] * 168 + Pdt;
ok

2021-11-05 10:42 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +            report = analysis.produceReport(10);
ok, done

2021-11-05 10:43 UTC, flomnes commented on src/solver/optimisation/opt_appel_solveur_lineaire.cpp
> +        Optimization::InfeasibleProblemAnalysis analysis(&Probleme, ".+::.+");
ok, done.

One idea could be to expose constraint types : bc_weekly, bc_daily, etc. And to allow the user to select what type of constraint they want to select. Not sure if useful though.

2021-11-05 10:45 UTC, flomnes commented on src/solver/infeasible-problem-analysis/report.cpp
> +void InfeasibleProblemReport::prettyPrint()
ok

2021-11-08 14:18 UTC, guilpier-code requested changes

2021-11-08 14:18 UTC, guilpier-code commented on src/solver/infeasible-problem-analysis/report.cpp
> +void InfeasibleProblemReport::prettyPrintImpl()
For me, **prettyPrintImpl** is meaningless, **logViolatedContraints()** or something  like that would be better.

2021-11-09 10:54 UTC, flomnes commented on src/solver/infeasible-problem-analysis/report.cpp
> +void InfeasibleProblemReport::prettyPrintImpl()
done

2021-11-22 10:11 UTC, guilpier-code approved these changes

2021-11-22 10:11 UTC, merged