UI: Change and rename "upstream/downstream" view
AntaresSimulatorTeam/Antares_Simulator pull request #468
Opened 2021-11-18 16:43 UTC by flomnes

# Map
![image](https://user-images.githubusercontent.com/26088210/142457798-792c404b-4a3b-42fa-85a0-1319119841b6.png)
# Before
![image](https://user-images.githubusercontent.com/26088210/142457869-cbb2bdb9-d048-4f41-9cdb-5b501adc360a.png)
# After
![image](https://user-images.githubusercontent.com/26088210/142458575-3dd3a02f-484d-4b46-bb3d-e64cf49d36d8.png)

2021-11-23 11:19 UTC, guilpier-code requested changes

2021-11-23 11:19 UTC, guilpier-code commented on src/ui/simulator/toolbox/input/connection.cpp
> +    std::map<Data::AreaName, std::vector<std::pair<Data::AreaLink*, bool>>> areaLinks;
**areaLinks** could be renamed into **areaToListOfLinks**, as **areaLinks** is a bit vague

2021-12-08 15:50 UTC, flomnes commented
With this PR, the flat view would become obsolete. Remove it ?

2022-01-14 10:46 UTC, flomnes commented on src/ui/simulator/toolbox/input/connection.cpp
> +    std::map<Data::AreaName, std::vector<std::pair<Data::AreaLink*, bool>>> areaLinks;
done

2022-01-27 11:22 UTC, flomnes commented
@guilpier-code Can we merge this ?

2022-01-27 11:35 UTC, JMJ-rte commented
Oui, on peut merger

2022-01-27 11:39 UTC, merged