GUI : scenario builder for links NTC
AntaresSimulatorTeam/Antares_Simulator pull request #497
Opened 2021-12-31 12:44 UTC by guilpier-code

2022-01-04 15:01 UTC, flomnes requested changes

2022-01-04 15:01 UTC, flomnes commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.cpp
> +    // pArea = nullptr;
Why comment this line ?

2022-01-05 15:56 UTC, flomnes requested changes
To be merged after #499

2022-01-05 15:59 UTC, flomnes commented
Fix 3 bugs and possibly a few issues

2022-01-06 14:16 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.cpp
> +    // pArea = nullptr;
Because dealing with areas is now done by class **ScBuilderRendererAreasAsRows**, not by **ScBuilderRendererBase** (parent of the latter).
**pArea** is not part of **ScBuilderRendererBase** anymore.

2022-01-12 17:44 UTC, flomnes approved these changes

2022-01-12 17:44 UTC, merged