Scenario builder ntc : use UI runtime
AntaresSimulatorTeam/Antares_Simulator pull request #499
Opened 2022-01-03 19:01 UTC by flomnes

2022-01-03 19:06 UTC, flomnes commented on src/ui/simulator/toolbox/components/map/nodes/connection.cpp
> +
revert this (see l. 265)

2022-01-03 19:13 UTC, flomnes commented on src/libs/antares/study/ui-runtimeinfos.h
> +    //! Vector containing links
pointers to links

2022-01-04 11:18 UTC, guilpier-code requested changes

2022-01-04 11:18 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
> +    Data::AreaLink::Vector* pLink;
**pLink** should be renamed **pListOfLinks** (or something like that) for more clarity.  Otherwise, one can think it refers to a single link.

2022-01-04 11:18 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
> +    Data::AreaLink::Vector* pLink;
Why is **pLink** a pointer, and not a reference ?

2022-01-04 11:18 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
> +        return "";
Why don't you return a **wxEmptyString** instead of a "" ?

2022-01-04 11:18 UTC, guilpier-code commented on src/libs/antares/study/ui-runtimeinfos.h
>      uint pLinkCount;
**pLinkCount** should remain private

2022-01-04 11:18 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/map/tools/remover.cpp
> +        ScenarioBuilderUpdater updaterSB(*Data::Study::Current::Get());
Question : what is this remover for ?

2022-01-04 11:18 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
> +      OnStudyChanged.connect(this, &ntcScBuilderRenderer::onStudyChanged);
**pLink** not initialized in the constructor

2022-01-04 12:57 UTC, flomnes commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
> +        return "";
done

2022-01-04 12:57 UTC, flomnes commented on src/libs/antares/study/ui-runtimeinfos.h
>      uint pLinkCount;
I will simply remove this unused member.

2022-01-04 12:57 UTC, flomnes commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
> +    Data::AreaLink::Vector* pLink;
done

2022-01-04 12:57 UTC, flomnes commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
> +    Data::AreaLink::Vector* pLink;
I tried using a reference at first, but I found that object `study` may not exist when an instance of `ntcScBuilderRenderer` is created. So I had to use a (possibly null) pointer instead.

2022-01-04 12:57 UTC, flomnes commented on src/ui/simulator/toolbox/components/map/tools/remover.cpp
> +        ScenarioBuilderUpdater updaterSB(*Data::Study::Current::Get());
It is called when the user removes one / multiple link or areas. Possibly both areas and links simultaneously.

![image](https://user-images.githubusercontent.com/26088210/148060131-545f1a33-d1f2-4055-bafb-7fa345ea3f88.png)

2022-01-04 12:57 UTC, flomnes commented on src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
> +    Data::AreaLink::Vector* pLink;
done

2022-01-04 12:58 UTC, flomnes reviewed
I accepted your remarks, some of sonar's and applied formatting rules.

2022-01-10 16:18 UTC, merged