New initial levels in scenario builder
AntaresSimulatorTeam/Antares_Simulator pull request #56
Opened 2020-10-01 09:53 UTC by guilpier-code

Apart from production + demand time series to be chosen by user, we add à new item to the scenario builder : hydro levels as start level for each year and area.
In a code point of view, this feature contains :

- Some refactorings to make code cleaner and make the new functionality easier to add
- Addition of a GUI component in the scenario builder for hydro levels.
- Addition of a new renderer for hydro levels. A renderer makes the bound between the GUI component and the underlying data and defines reactions when user interacts with GUI component.
- Addition of a data container for hydro levels (storing, loading, saving... data)
- Convey of the levels scenario data to the study
- Handling levels in the simulation from data contained in the study

2020-10-05 07:31 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/rules.cpp
> -			if (not updaterMode)
Remove updaterMode option ?

2020-10-05 08:49 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/sets.h
> -		bool inUpdaterMode;
Remove if updater mode feature ?

2020-10-05 08:51 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/scBuilderDataInterface.h
> +		void add_value(uint x, uint y, String value) = 0;
J'aurais plutot nommer la méthode `set_value`. On ne rajoute pas de colonne ou de ligne à la matrice on définit une de ces cellules. Correspondance entre `get_value `et `set_value`.

2020-10-05 08:54 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/rules.cpp
> +			case 'v':
On peut supporter des labels avec plusieurs caractères si l'on remplace `kindc` par un `string`.

2020-10-05 09:32 UTC, jmkerloch requested changes
Il faut discuter du comportement actuel pour l'affichage et la récupération des pourcentages depuis l'IHM.

2020-10-05 09:32 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/hydroLevelsData.h
> +	inline double hydroLevelsData::get_value(uint x, uint y) const { return pHydroLevelsRules.entry[y][x] * 100.; }
Je pense qu'il serait préférable de gérer l'affichage des valeurs en pourcentage directement dans l'IHM mais pas dans le modèle.
Si on utilise la méthode `double hydroLevelsData::get_value(uint x, uint y)` on se retrouve une valeur entre 0 et 100 alors que la données stockées est entre 0 et 1.

2020-10-05 09:32 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/hydroLevelsData.cpp
> +	void hydroLevelsData::add_value(uint x, uint y, String value)
La méthode `add_value `ne devrait pas prendre de `string `mais un `double`.
La division par 100.0 devrait être effectuée dans l'IHM et pas le modèle

2020-10-05 09:34 UTC, jmkerloch commented on src/libs/antares/study/parameters.cpp
> +		if (key == "custom-scenario")
Il faut gérer l'ancienne balise.

2020-10-05 09:51 UTC, jmkerloch requested changes
Il faut qu'il y ait une vérification des données lues depuis le fichier .dat

![image](https://user-images.githubusercontent.com/53606373/95065240-0bd80400-0701-11eb-8b38-84e4abe3c5d8.png)

2020-10-05 09:51 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/hydroLevelsData.h
> +	inline void hydroLevelsData::set(uint areaindex, uint year, String value)
Il s'agit de la méthode appelée lors de la lecture des fichiers .dat scenariobuilder.dat.
Il n'y a dans ce cas aucun controle sur la valeur passée.
On peut donc avoir des valeurs ne correspondant pas à des pourcentages.

2020-10-05 09:53 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/TSnumberData.h
> +		CString<512, false> get_prefix() const = 0;
Est ce qu'on ne pourrait pas passer à des `std::string` ?

2020-10-05 10:00 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/rules.cpp
>  			case 'l':
J'aurais changé le `switch case` en `else if` afin de supporter des labels avec plusieurs caractères.
Proposition aussi de récupérer aussi directement depuis les méthodes `get_prefix `pour garantir la cohérence des prefix.
Dans ce cas `get_prefix `ne doit pas retourner de virgule. Ceci doit être géré lors de l'écriture.

2020-10-20 08:15 UTC, guilpier-code commented on src/libs/antares/study/scenario-builder/sets.h
> -		bool inUpdaterMode;
Bonne question, j'ai peut-être supprimé cette variable un peu trop rapidement.
D'abord elle ne concerne que des logs (selon sa valeur, on imprime du texte sur cmd/terminal ou pas), donc la supprimer n'a pas d'incidence sur les calculs.
J'ai pensé que cette variable booléenne ne peut avoir qu'une seule valeur, à la lecture du code, ce qui la rend inutile.
Mais en creusant, son inutilité ne paraît plus si évidente, je pense même qu'elle est utile.
Je la remet en service.

2020-10-20 09:01 UTC, guilpier-code commented on src/libs/antares/study/scenario-builder/scBuilderDataInterface.h
> +		void add_value(uint x, uint y, String value) = 0;
ok

2020-10-20 13:05 UTC, guilpier-code commented on src/libs/antares/study/scenario-builder/rules.cpp
> +			case 'v':
ok

2020-10-20 14:27 UTC, guilpier-code commented on src/libs/antares/study/scenario-builder/hydroLevelsData.h
> +	inline double hydroLevelsData::get_value(uint x, uint y) const { return pHydroLevelsRules.entry[y][x] * 100.; }
ok, c'est d'ailleurs vrai aussi pour les autres types de scenario (load, wind, thermal, ...)

2020-10-27 15:18 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/sets.cpp
> -				uint value = p->value.to<uint>();
Pourquoi on supprime le passage en int dans la lecture et on le délegue à loadFromInstrs ? Si on a une erreur sur la valeur donnée il vaut mieux la vérifier à la lecture.

2020-10-27 15:40 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/hydroLevelsData.h
> +	inline void hydroLevelsData::set(uint areaindex, uint year, String value)
Ajout de méthodes pour vérification des valeurs passées `fromStringToTSnumber fromStringToHydroLevel`

2020-10-27 15:51 UTC, jmkerloch commented on src/libs/antares/study/scenario-builder/sets.cpp
> -				uint value = p->value.to<uint>();
OK vérification effectuée dans le code de lecture.
Par contre par de warning si valeur incorrecte. A voir si comportement à modifier car non présent avant cette feature.

2020-10-27 16:11 UTC, jmkerloch commented on src/solver/simulation/timeseries-numbers.h
> +	// void ApplyCustomScenario(Data::Study& study);
Commentaires à supprimer

2020-10-27 16:51 UTC, jmkerloch approved these changes
OK pour moi suite à prise en compte des commentaires.

2020-11-04 08:42 UTC, merged