Link upper banner : update the banner (or board) when changing of tab
AntaresSimulatorTeam/Antares_Simulator pull request #572
Opened 2022-02-22 16:46 UTC by guilpier-code

When we change a link property (transmission capacity usage, hurdle costs usage, ...) in the upper banner, and than
change of tab  (for example from Transmission capacities to Parameters), his upper banner is not properly refreshed.
This is fixed here.

See issue #566

2022-02-23 13:18 UTC, guilpier-code commented on src/ui/simulator/windows/connection.cpp
> +// Events to update a link property in all Interconnection objects (upper banner for any link view)
I tried to put the definition of this events inside class  **Interconnection**, where it belongs I think.
But it does not work : It compiles but these events are not caught, and so the view update is not done.
Strange. Maybe it should be investigated.

2022-02-23 13:18 UTC, guilpier-code commented on src/ui/simulator/windows/connection.cpp
> +    onLinkCaptionChanges.connect(this, &Interconnection::updateLinkCaption);
Possible improvement : each button of the upper banner (hurdle costs usage, transmission capacities usage, ...) should be objects inner to the class  **Interconnection**, probably created outside this class and passed to its constructor. All these little button classes have things in common, they could inherit from an mother abstract class.

2022-02-23 13:23 UTC, guilpier-code commented on src/ui/simulator/windows/connection.cpp
> +    onLinkCaptionChanges.connect(this, &Interconnection::updateLinkCaption);
Another thing about the previous refactoring : passing button objects to the **Interconnection** constructor would have another advantage than modularity. these objects could be shared by the 2 **Interconnection** objects (that is te 2 tabs **Parameters** and **Transmission capacities**), and we should not need to throw any events to update the button values in the other tab.

2022-02-23 13:27 UTC, flomnes approved these changes
Can be merged as is. Create an issue to solve this later ?

2022-02-23 15:16 UTC, flomnes requested changes
De-duplicate objects ?

2022-02-24 12:15 UTC, flomnes approved these changes

2022-02-24 15:32 UTC, merged