Save NTC timeseries even if all coefficients are zero
AntaresSimulatorTeam/Antares_Simulator pull request #595
Opened 2022-03-11 17:14 UTC by flomnes

2022-03-14 10:00 UTC, guilpier-code requested changes

2022-03-14 10:00 UTC, guilpier-code commented on src/libs/antares/array/matrix.hxx
> +    if ((not print_dimensions and containsOnlyZero(predicate)) && !saveEvenIfAllZero)
I would put it that way : 
```
if (not print_dimensions and (containsOnlyZero(predicate) and not saveEvenIfAllZero))
    return
```
more clear for me

2022-03-14 10:30 UTC, flomnes commented on src/libs/antares/array/matrix.hxx
> +    if ((not print_dimensions and containsOnlyZero(predicate)) && !saveEvenIfAllZero)
Operator `and` is associative _ie_ `(x and y) and z == x and (y and z)`, but I agree.

In such cases, you can suggest changes using this button 
![image](https://user-images.githubusercontent.com/26088210/158154564-9e84c4f6-ef8e-42c1-ac93-9933943defc5.png)

2022-03-16 12:50 UTC, guilpier-code approved these changes

2022-03-16 12:56 UTC, merged