Refactor scripts for tests
AntaresSimulatorTeam/Antares_Simulator pull request #601
Opened 2022-03-15 16:41 UTC by guilpier-code

2022-03-24 10:14 UTC, flomnes requested changes
- Remove old scripts ?
- You upgraded some submodules, is it intended ?

2022-03-24 10:14 UTC, flomnes commented on src/tests/examples/antares_test_utils.py
> +    return dir_list[0]
Place in a new .py file ?

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +	"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +	"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +				return line.split('=')[1].strip()
There is no need to read the entire file into a `list`. Instead, you can read the file line-by-line with something like
```py
for line in f:
    # Do what you want with the line
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +				return line.split('=')[1].strip()
There is no need to read the entire file into a `list`. Instead, you can read the file line-by-line with something like
```py
for line in f:
    # Do what you want with the line
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Remove this comment

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +				content_out.append(variable + " = " + value + "\n")
Same comment as above

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +				content_out.append(variable + " = " + value + "\n")
Same comment as above

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_modifier.py
> +from actions_on_study.study_input_handler import *
```suggestion
from actions_on_study.study_input_handler import *
```
```suggestion
import actions_on_study.study_input_handler as input_handler
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_modifier.py
> +from actions_on_study.study_input_handler import *
```suggestion
from actions_on_study.study_input_handler import *
```
```suggestion
import actions_on_study.study_input_handler as input_handler
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_modifier.py
> +        self.study_input_handler = study_input_handler(str(self.study_path))
`study_input_handler` could accept a path instead of a string

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_modifier.py
> +        self.study_input_handler = study_input_handler(str(self.study_path))
`study_input_handler` could accept a path instead of a string

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_run.py
> +        self.raise_exception_at_failure = False
```suggestion
        self.raise_exception_at_failure = False
```
```suggestion
        self.raise_exception_on_failure = False
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_run.py
> +        self.raise_exception_at_failure = False
```suggestion
        self.raise_exception_at_failure = False
```
```suggestion
        self.raise_exception_on_failure = False
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/actions_on_study/study_run.py
> +        self.raise_exception_at_failure = False
```suggestion
        self.raise_exception_at_failure = False
```
```suggestion
        self.raise_exception_on_failure = False
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +        check_interface.__init__(self, study_path)
```suggestion
        check_interface.__init__(self, study_path)
```
```suggestion
        super().__init__(self, study_path)
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +        check_interface.__init__(self, study_path)
```suggestion
        check_interface.__init__(self, study_path)
```
```suggestion
        super().__init__(self, study_path)
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +            raise_assertion("Hydro level not correct : %.2f" % reservoir_levels[self.date_in_hours])
```suggestion
            raise_assertion("Hydro level not correct : %.2f" % reservoir_levels[self.date_in_hours])
```
```suggestion
            raise_assertion("Hydro level not correct : %.2f, expected %.2f" % (reservoir_levels[self.date_in_hours], self.level))
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +            raise_assertion("Hydro level not correct : %.2f" % reservoir_levels[self.date_in_hours])
```suggestion
            raise_assertion("Hydro level not correct : %.2f" % reservoir_levels[self.date_in_hours])
```
```suggestion
            raise_assertion("Hydro level not correct : %.2f, expected %.2f" % (reservoir_levels[self.date_in_hours], self.level))
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_logs_content.py
> +            raise_assertion("Unknown log level : %s" % log_level)
`raise_assertion` might be easier to use with this prototype
```py
def check(condition, message):
   if not condition:
       # Print message with the custom format from assertions.py
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_logs_content.py
> +            raise_assertion("Unknown log level : %s" % log_level)
`raise_assertion` might be easier to use with this prototype
```py
def check(condition, message):
   if not condition:
       # Print message with the custom format from assertions.py
```

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +        print("running check : %s" % self.__class__.__name__)
I think that this `print` should be defined in the interface. Also, I'm not sure using class names is a good idea, the name of the check should be defined as a string.

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +        print("running check : %s" % self.__class__.__name__)
I think that this `print` should be defined in the interface. Also, I'm not sure using class names is a good idea, the name of the check should be defined as a string.

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/unfeasible_problem.py
> +        """
Remove this ? Is this something we want to keep ?

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/check_on_results/unfeasible_problem.py
> +        """
Remove this ? Is this something we want to keep ?

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/find_and_check_studies.py
> +ROOT_FOLDER = Path('d:/') / 'Users' / 'pierregui' / "Desktop" / "python-test" / "valid-defaillance"
We probably don't want to keep this here

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/find_and_check_studies.py
> +ROOT_FOLDER = Path('d:/') / 'Users' / 'pierregui' / "Desktop" / "python-test" / "valid-defaillance"
We probably don't want to keep this here

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/fixtures.py
> +    print("\nTest begins")
Is this `print` useful ?

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/fixtures.py
> +    print("\nTest begins")
Is this `print` useful ?

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/fixtures.py
> +    print('\nEnd of test')
Same question as above

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/fixtures.py
> +    print('\nEnd of test')
Same question as above

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/utils/find_output.py
> +
Remove this

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/utils/find_output.py
> +
Remove this

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/utils/find_reference.py
> +from utils.assertions import raise_assertion
Unused import

2022-03-24 10:14 UTC, flomnes commented on src/tests/run-study-tests/utils/find_reference.py
> +
Unused imports

2022-03-24 15:35 UTC, guilpier-code commented on src/tests/run-study-tests/check_on_results/unfeasible_problem.py
> +        """
These comments are a an abandoned start for adding some new checks (more like a reminder if you like). These new checks were actually added in the branch regarding tests based on the readings of json files.

2022-03-24 15:50 UTC, guilpier-code commented on src/tests/run-study-tests/find_and_check_studies.py
> +ROOT_FOLDER = Path('d:/') / 'Users' / 'pierregui' / "Desktop" / "python-test" / "valid-defaillance"
ok, I'll do better, but in the end, the whole file should be removed, as we have better in the next branch (tests built with json files)

2022-03-28 14:53 UTC, flomnes commented on src/tests/examples/antares_test_utils.py
> +    return dir_list[0]
Place in a new .py file ?

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +				return line.split('=')[1].strip()
done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +	"""
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +		"""
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_input_handler.py
> +				content_out.append(variable + " = " + value + "\n")
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_modifier.py
> +from actions_on_study.study_input_handler import *
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_modifier.py
> +        self.study_input_handler = study_input_handler(str(self.study_path))
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/actions_on_study/study_run.py
> +        self.raise_exception_at_failure = False
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +        check_interface.__init__(self, study_path)
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +        print("running check : %s" % self.__class__.__name__)
done, with the help of a decorator.

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/check_on_results/check_hydro_level.py
> +            raise_assertion("Hydro level not correct : %.2f" % reservoir_levels[self.date_in_hours])
done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/fixtures.py
> +    print("\nTest begins")
not really, I remove it.

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/fixtures.py
> +    print('\nEnd of test')
Same answer

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/utils/find_output.py
> +
Done

2022-03-29 08:38 UTC, guilpier-code commented on src/tests/run-study-tests/utils/find_reference.py
> +from utils.assertions import raise_assertion
Not sure if any import was useless here, but after corrections (for other purposes), every import is useful

2022-04-19 12:14 UTC, flomnes commented
- Indentation on Linux
- Windows : merge develop for `vcpkg`

2022-04-19 12:14 UTC, flomnes commented
- Indentation on Linux
- Windows : merge develop for `vcpkg`

2022-05-03 07:52 UTC, flomnes commented
Contained by #659

2022-05-03 07:52 UTC, closed without merging