Adequacy Patch - Curtailment Sharing Rule 11/05
AntaresSimulatorTeam/Antares_Simulator pull request #679
Opened 2022-05-11 09:58 UTC by hugo-antoine-rtei

Hello Florian,

Here's the latest version of the adequacy patch we have at RTEi. Let me know what you think. Milos wanted me to mention that he plans to re-pack (do refactoring) - put all the variables for quadratic optimization inside new class (and its instance) that we will create.

2022-05-19 16:50 UTC, guilpier-code requested changes

2022-05-19 16:50 UTC, guilpier-code commented on src/ext/yuni/src/yuni/core/math/math.h
> +/*!
Please do not modify Yuni library : it's not ours and we don't want to maintain it.

2022-05-19 16:50 UTC, guilpier-code commented on src/ext/yuni/src/yuni/core/math/math.hxx
> +template<class T>
Please do not modify Yuni library : it's not ours and we don't want to maintain it.

2022-05-19 16:50 UTC, guilpier-code commented on src/libs/antares/study/fwd.h
> +    adqPatchPTOIsDens = 0,
As you always use enum name before enum value (ex : **AdequacyPatchPTO::adqPatchPTOIsDens**), you don't need to re-specify the **adqPatch** in the value.
 ```C++
enum AdqPatchPTO
{
    isDens = 0,
    isLoad
}; 
```
should be ok

2022-05-19 16:50 UTC, guilpier-code commented on src/libs/antares/study/fwd.h
> +enum AdqPatchThresholdsIndex
This **enum** **AdqPatchThresholdsIndex** exists because you declare an array of 2 thresholds. This array is not required here and we should have 2 separate variables for the 2 thresholds.
Eventually, this **enum** should be removed.
Please see comments in **adequacy-patch-options.cpp**, **parameters.cpp** and **sim_calcul_economique.cpp**

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
> +    for (uint i = 0; i != (uint)Data::AdequacyPatch::adqPatchThresholdsMax; ++i)
The notion of seed does not have anything to do with what we deal with here, that is adequacy patch thresholds.
So this array **pEditSeeds** should be renamed.

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
> +        pEditSeeds[i] = nullptr;
As a matter of fact, we should not have a size so small for array **pEditSeeds** (size = 2). We have a similar array in **advanced.cpp**, it is bigger,  but is not an example to follow, in my opinion. 
At least here, this array is over-engineering. It forces you (it seems) to make several loops over its elements in the current file, and that makes the code complicated and difficult to read.
Please separate the handling the 2 thresholds.

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
> +void AdequacyPatchOptions::onEditSeedTSDraws(wxCommandEvent& evt)
Seed and draws are not relevant when we talk about thresholds for adequacy patch, don't you think ? :-)

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/sim_calcul_economique.cpp
> +          = parameters.seedAdqPatch[adqPatchThresholdInitiateCurtailmentSharingRule];
Array **seedAdqPatch** is ill-named (we are talking about thresholds, not seeds) and unnecessary. It makes code mode complicated than it should.

2022-05-19 16:50 UTC, guilpier-code commented on src/libs/antares/study/parameters.cpp
> +          d.seedAdqPatch[AdequacyPatch::adqPatchThresholdInitiateCurtailmentSharingRule]);
Please replace **seedAdqPatch** by 2 separate data members and then save and load them accordingly.

2022-05-19 16:50 UTC, guilpier-code commented on src/libs/antares/study/parameters.cpp
> +    // Adequacy patch
Perhaps you could integrate all adequacy patch reset in a single function **resetAdqPatchParameters**

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/variable/economy/lmrViolations.h
> +/*
Please rename this file into **localMatchingViolations.h**

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +}
To be clearer we should have something like : 
```C++
std::set<int> Economy::getHoursRequiringCurtailmentSharing()
{
    vector<double> sumENS = calculateENSoverAllAreasForEachHour()
    return identifyHoursForCurtailmentSharing()
}
```
Note that we should not need **pProblemeHebdo** as we should make this function a method of economy class. Please also see review on **economy.cpp** made in pull request #657.

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +            }
Please see review on **economy.cpp** made in pull request https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/657 : We should encapsulate the block above and make polymorphism play its part here.
Eventually, instead of this block (line 234 - 261), we should have 
```c++
theWeeklyProblem->run(/*some arguments ?*/)
```

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +                std::set<int> hoursInWeekTriggerCsrSet;
Proposition : 
```C++
std::set<int> hoursRequiringCurtailmentSharing = getHoursRequiringCurtailmentSharing()
```

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +                if (hoursInWeekTriggerCsrSet.size() > 0)
We don't need the **if** statement : the loop over the set of years is sufficient. If the set's size is empty there won't be a loop, as you know.

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +                    pProblemesHebdo[numSpace]->hourlyCsrProblems.clear();
If we clear the curtailment sharing problem before the loop over hours, we should not need to clear it after this loop.

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +                        pProblemesHebdo[numSpace]->hourlyCsrProblems.push_back(hourlyCsrProblem);
```C++
pProblemesHebdo[numSpace]->hourlyCsrProblems.push_back(hourlyCsrProblem);
```
The storage of the hourly curtailment sharing problem here seems to be useless.

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +}
As said below, **hourlyCsrProblem** should have method **run()**, which could be as follows : 

```C++
void hourlyCsrProblem::run()
{
    // Note that pWeeklyProblem is a data member of our curtailment sharing problem
    calculateCsrParameters();
    
    OPT_LiberationProblemesSimplexe(pWeeklyProblem); 
    OPT_ConstruireLaListeDesVariablesOptimiseesDuProblemeQuadratique_CSR(pWeeklyProblem, hourlyCsrProblem);
    ...
}
```
Note that all **OPT_something** methods called here should be private methods of our hourly curtailment sharing problem call. They could be renamed into **buildProblemVariables**, **buildProblemConstraints** and so on. Note that these previous functions could simply call the procedural **OPT_something** functions that are so common in this code area.
```C++
void hourlyCsrProblem::buildProblemVariables()
{
    OPT_ConstruireLaListeDesVariablesOptimiseesDuProblemeQuadratique_CSR(pWeeklyProblem, this);
}
```

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/economy.cpp
> +                        OPT_OptimisationHourlyCurtailmentSharingRule(hourlyCsrProblem);
The hourly curtailment sharing problem needs the previously run weeky problem, right ?
So I guess we should have something like : 
```C++
for (int hourInWeek : hoursInWeekTriggerCsrSet)
{
      HOURLY_CSR_PROBLEM hourlyCsrProblem(hourInWeek, pProblemesHebdo[numSpace]);
      hourlyCsrProblem.run();
}
```
And that's it !

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/optimisation/opt_appel_solveur_quadratique.cpp
> +}
Perhaps we should split this long function into smaller ones (to make the code clearer and show only the structure of what it does) : 
```C++
bool OPT_AppelDuSolveurQuadratique_CSR(PROBLEME_ANTARES_A_RESOUDRE* ProblemeAResoudre, HOURLY_CSR_PROBLEM& hourlyCsrProblem)
{
   PROBLEME_POINT_INTERIEUR Probleme;
   setInteriorPointProblem(Probleme);
   PI_Quamin(&Probleme); // resolution
   ProblemeAResoudre->ExistenceDUneSolution = Probleme.ExistenceDUneSolution;
   if (ProblemeAResoudre->ExistenceDUneSolution == OUI_PI)
   {
       storeInteriorPointResults(ProblemeAResoudre);
       return true;
   }
   else
   {
       handleInteriorPointError(ProblemeAResoudre);
       return false;
   }
}

```
Here I am mixing french and english, but you see the point

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
> +void OPT_ConstruireLaMatriceDesContraintesDuProblemeQuadratique_CSR(
As for curtailment sharing problem resolution (see review of **opt_appel_solveur_quadratique.cpp**), we could split this long function into smaller ones : 
```C++
void OPT_ConstruireLaMatriceDesContraintesDuProblemeQuadratique_CSR(PROBLEME_HEBDO* ProblemeHebdo,
  HOURLY_CSR_PROBLEM& hourlyCsrProblem)
{
    Pi = (double*)MemAlloc(ProblemeAResoudre->NombreDeVariables * sizeof(double));
    Colonne = (int*)MemAlloc(ProblemeAResoudre->NombreDeVariables * sizeof(int));

    setConstraintsOnENS(ProblemeHebdo, hourlyCsrProblem, Pi, colonne);
    setConstraintsOnFlows(ProblemeHebdo, hourlyCsrProblem, Pi, colonne);
    ...
    setBindingConstraints(ProblemeHebdo, hourlyCsrProblem, Pi, colonne);
}
```
It's still not satisfactory but it would be better

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
> +  PROBLEME_HEBDO* ProblemeHebdo,
Same remark as in **opt_construction_matrice_des_contraintes_cas_quadratique.cpp**

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
> +void OPT_InitialiserLesBornesDesVariablesDuProblemeQuadratique_CSR(
same remark as in **opt_construction_matrice_des_contraintes_cas_quadratique.cpp**

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
> +void OPT_InitialiserLesCoutsQuadratiques_CSR(PROBLEME_HEBDO* ProblemeHebdo,
same remark as in **opt_construction_matrice_des_contraintes_cas_quadratique.cpp**

2022-05-19 16:50 UTC, guilpier-code commented on src/solver/simulation/sim_structure_probleme_economique.h
> +class HOURLY_CSR_PROBLEM
Has said earlier, a curtailment sharing problem should run with the help of public method calling private methods (see review on **economy.cpp**)

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/application/main/menu.cpp
> +                     mnIDOptionAdequacyPatchConfigure,
**mnIDOptionAdequacyPatchConfigure** ? What you mean is more **mnIDOptionAdequacyPatchOptions**, don't you ?

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/application/main/options.cpp
> +void ApplWnd::evtOnOptionsAdequacyPatchConfigure(wxCommandEvent&)
Rather : 
```C++
void ApplWnd::evtOnOptionsAdequacyPatchOptions(wxCommandEvent&)
```
no ?

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.cpp
> +        bool vir = s == "0" || s == "virtual" || s == "virtual area";
Please prefer : 
```C++
bool Virtual = s == "0" || s == "virtual" || s == "v";
bool Inside = s.to<int>() == 2 || s == "inside" || s == "i";
bool Outside = s.to<int>() == 1 || s == "outside" || s == "o";
```
Not sure the user will have the patience to write **"physical area inside patch"** in the cell :-)

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
> +static void SubTitle(wxWindow* parent, wxSizer* sizer, const wxChar* text, bool margintop = true)
For now, you don't use **margintop** argument, we should think about removing it

2022-05-19 16:50 UTC, guilpier-code commented on src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
> +static void ResetButtonNTC(Component::Button* button, bool value)
prefer : 
```C++
static void updateButton(Component::Button* button, bool value)
```
Furthermore, we have 3 **reset** (or **update**)  functions that do the same thing.
We should avoid duplicate code.

For the PTO, the call could be : 
```C++
using namespace Data::AdequacyPatch; // Somewhere up in the code
....
bool isPTOload = (study.parameters.adqPatchPriceTakingOrder == AdqPatchPTO::isLoad) ? true : false;
updateButton(pBtnAdequacyPatchPTO, isPTOload);
```
See review on **fwd.h** to shorten a bit the enum values

2022-06-03 14:57 UTC, Milos-RTEi commented
Hello @flomnes. I merged two branches into feature/adq-patch, under review here.  
1- feature/rte-comments-csr-batch1: RTEi implementation of RTE comments on CSR.
2- feature/adq-patch-2: RTEi implementation of RTE local matching rule comments (outdated a little bit since you worked on local-matching-rule branch but we will take care of that) into CSR solution.

2022-06-09 13:46 UTC, flomnes reviewed
Do not use `ProblemeHebdo->ProblemeAResoudre`, use a new instance of `PROBLEME_POINT_INTERIEUR` instead, make sure to allocate arrays to the proper size (number of variables, number of constraints, number of non-zero coefficients in the constraint matrix)

2022-06-09 13:46 UTC, flomnes commented on src/solver/simulation/economy.cpp
> +    double temp[nbHoursInAWeek] = {0};
Use `std::vector`

2022-06-09 13:46 UTC, flomnes commented on src/solver/optimisation/adequacy_patch.cpp
> +    calculateCsrParameters(pWeeklyProblemBelongedTo, *this);
Is it necessary to pass `*this`, consider making this function a member-function.

2022-06-09 13:46 UTC, flomnes commented on src/solver/optimisation/adequacy_patch.cpp
> +void calculateCsrParameters(PROBLEME_HEBDO* ProblemeHebdo, HOURLY_CSR_PROBLEM& hourlyCsrProblem)
```suggestion
void HOURLY_CSR_PROBLEM::calculateCsrParameters(PROBLEME_HEBDO* ProblemeHebdo)
```

2022-06-09 13:46 UTC, flomnes commented on src/libs/antares/study/fwd.h
> +const float adqPatchDefaultValueThresholdDisplayLocalMatchingRuleViolations = 500.0;
`0` as a default value, compare as follows `if (value > threshold)`

2022-06-09 13:46 UTC, flomnes commented on src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
> +                else
```suggestion
                else if(ProblemeHebdo->adqPatch->PriceTakingOrder
                    == Data::AdequacyPatch::AdqPatchPTO::isDens)
```

2022-06-09 13:46 UTC, flomnes commented on src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
> +                                                            HOURLY_CSR_PROBLEM& hourlyCsrProblem)
```suggestion
void OPT_InitialiserLeSecondMembreDuProblemeQuadratique_CSR(PROBLEME_POINT_INTERIEUR* ProblemeHebdo,
                                                            HOURLY_CSR_PROBLEM& hourlyCsrProblem)
```

2022-06-13 15:49 UTC, closed without merging