Hide DENS if adq-patch is disabled
AntaresSimulatorTeam/Antares_Simulator pull request #767
Opened 2022-07-11 09:45 UTC by flomnes

2022-07-11 15:38 UTC, guilpier-code requested changes

2022-07-11 15:38 UTC, guilpier-code commented on src/libs/antares/study/parameters.h
> +        bool include;
I guess `bool include` inside `struct AdequacyPatch` replaces former `bool adequacyPatch`.
**include** is unclear to me, maybe **activated** or **used** would be better.
I know that **include** is a part of **include-adequacypatch** in the **generaldata.ini**, but still, in the code (but not in **generaldata.ini**), the associated parameter could be renamed.

2022-07-11 16:14 UTC, flomnes commented on src/libs/antares/study/parameters.h
> +        bool include;
Done. Kept the same name in the study, renamed in the code.

2022-07-13 07:43 UTC, guilpier-code commented on src/libs/antares/study/parameters.h
> +        bool include;
You made the change **include** --> **enabled** in PR

2022-07-13 07:44 UTC, guilpier-code approved these changes

2022-07-13 07:46 UTC, merged