Make adequacy patch parameters future-proof
AntaresSimulatorTeam/Antares_Simulator pull request #768
Opened 2022-07-11 10:55 UTC by flomnes

2022-07-11 16:09 UTC, guilpier-code requested changes

2022-07-11 16:09 UTC, guilpier-code commented on src/libs/antares/study/parameters.cpp
> +                                      uint)
For information, the last argument of **every SGDIntLoadFamily_some_section(..., uint)** is useless. We should remove it for every function.
Either we correct it in this PR or we create a ticket. Correcting it now would be very quick.

2022-07-11 16:24 UTC, flomnes commented on src/libs/antares/study/parameters.cpp
> +                                      uint)
The legacy function uses this argument as a study version number.

https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/eacccf28ca43f2d714365c1da73a41ee4136c57e/src/libs/antares/study/parameters.cpp#L923-L927

2022-07-12 09:22 UTC, guilpier-code requested changes

2022-07-12 09:22 UTC, guilpier-code commented on src/libs/antares/study/parameters.cpp
> +                                      uint)
ok. 
here I correct my previous remark.
Note that this new remark leads to a possible refactor. Let's discuss if we need to take this remark into account.

Every **Callback** function that is a value of the map **sectionAssociatedToKeysProcess** do not need the last **uint version** argument. the **Callback** type should also loose the unnecessary argument.
So **SGDIntLoadFamily_Legacy** is kind of apart from the  **SGDIntLoadFamily**.

Another point : the 4th argument **const String&** (which the raw value, before the value is turned to lower case) is only used by the body of **SGDIntLoadFamily_General**. So there is a kind of repetition in the list of arguments of this family of function, example : 
```C++
handleAllKeysInSection(*this, p->key, value, p->value, version)
```
We could try to remove one of the **value** argument as well.

2022-07-12 12:59 UTC, flomnes commented on src/libs/antares/study/parameters.cpp
> +                                      uint)
See #774

2022-07-13 07:41 UTC, guilpier-code approved these changes

2022-07-13 09:18 UTC, merged