Use generic writer to write MPS files, criterion, interco, etc.
AntaresSimulatorTeam/Antares_Simulator pull request #807
Opened 2022-08-18 10:52 UTC by flomnes

2022-09-07 15:06 UTC, guilpier-code requested changes

2022-09-07 15:06 UTC, guilpier-code commented on src/libs/antares/study/mps.cpp
> +                                                     int n) const
What is argument **n** ? We should give it a more explicit name. As it has a default value (=0) and is never given another value, why appending a "-0" in the file name.

2022-09-07 15:06 UTC, guilpier-code commented on src/libs/antares/study/mps.cpp
> +                                                     uint numSpace,
The function name is not related to what it does, we should rename it **createWeeklySimulationPath**.
The source file hasn't got a good name as well.

2022-09-07 15:06 UTC, guilpier-code commented on src/solver/utils/mps_utils.cpp
>  static void printHeader(Clob& Flot, int NombreDeVariables, int NombreDeContraintes)
**Flot** does mean anything to me. Why not **buffer** or **memoire_tampon** (french)

2022-09-07 15:06 UTC, guilpier-code commented on src/solver/utils/mps_utils.cpp
> +      = study->createFileIntoOutputWithExtension("problem-fixed-part", "mps", numSpace);
As I said in **mps.cpp** review, prepending output folder was removed from the file path

2022-09-07 15:06 UTC, guilpier-code commented on src/solver/optimisation/opt_export_structure.cpp
> +        Yuni::Clob Flot;
**Flot** ==> **buffer** ? **memoire_tampon** ?

2022-09-07 15:06 UTC, guilpier-code commented on src/solver/simulation/solver.hxx
> +    study.setWriter(pResultWriter);
As said earlier review made on the "zip" matter, the **study->parameters** already has the info to create a writer, we should create it in the study after reading this info, and pass this writer to component that need it.

2022-09-07 15:06 UTC, guilpier-code commented on src/solver/utils/mps_utils.cpp
> +void OPT_EcrireJeuDeDonneesLineaireAuFormatMPS(void* Prob, uint numSpace, int n)
Parameter **n** is unused (and should be renamed [**optimNumber** ?])

2022-09-07 15:06 UTC, guilpier-code commented on src/libs/antares/study/mps.cpp
> -    // Preparing the filename where to write the MPS file
I suppose that the use of the output folder will be restored in this function.
So this function needs the study to get it.
That said, this function should not belong to the study : the study class is big enough and this belongs more to the place it is used : for instance **mps_utils.h/cpp**

2022-09-08 13:00 UTC, flomnes commented on src/solver/utils/mps_utils.cpp
> +void OPT_EcrireJeuDeDonneesLineaireAuFormatMPS(void* Prob, uint numSpace, int n)
It's now used

2022-09-08 14:48 UTC, flomnes commented on src/solver/simulation/solver.hxx
> +    study.setWriter(pResultWriter);
Will do it elsewhere

2022-09-08 14:48 UTC, flomnes commented on src/libs/antares/study/mps.cpp
> +                                                     int n) const
name was changed, more expressive

2022-09-08 14:49 UTC, flomnes commented on src/libs/antares/study/mps.cpp
> +                                                     uint numSpace,
Renamed into `getFilenameWithExtension`

2022-09-08 15:44 UTC, flomnes commented
@guilpier-code DONE

2022-09-26 09:54 UTC, flomnes commented on src/libs/antares/study/mps.cpp
> +                                                     int n) const
This will be obsolete with the MPS writer interface

2022-09-27 14:06 UTC, guilpier-code approved these changes

2022-10-10 15:43 UTC, merged