I/O error handling
AntaresSimulatorTeam/Antares_Simulator pull request #822
Opened 2022-08-23 09:23 UTC by flomnes

2022-08-23 10:37 UTC, flomnes commented on src/solver/writer/immediate_file_writer.cpp
> +    return true;
```suggestion
    return createDirectoryHierarchy(root, entryPath.c_str());
```

2022-08-24 11:57 UTC, flomnes commented on src/solver/writer/immediate_file_writer.cpp
> +    }
```suggestion
    if (prepareDirectoryHierarchy(pOutputFolder, entryPath, output))
    {
        IOFileSetContent(output, entryContent);
    }
```

2022-09-13 09:24 UTC, guilpier-code requested changes

2022-09-13 09:24 UTC, guilpier-code commented on src/solver/writer/zip_writer.cpp
> +    fillInfo(file_info, pEntryPath);
Why not : 
```C++
mz_zip_file file_info = setInfo(file_info, pEntryPath);
```
?

2022-09-13 09:24 UTC, guilpier-code commented on src/solver/writer/zip_writer.cpp
> +    int ret;
why not directly : 
```C++
int ret = mz_zip_writer_close(pZipHandle);
```
?

2022-09-14 12:19 UTC, merged