Fix potential segfault with many BCs, refactor
AntaresSimulatorTeam/Antares_Simulator pull request #853
Opened 2022-09-05 12:01 UTC by flomnes

2022-09-06 07:54 UTC, flomnes commented on src/solver/variable/surveyresults/surveyresults.cpp
> +    // Marginal price
Determine at compilation ?

2022-09-06 14:56 UTC, guilpier-code requested changes

2022-09-06 14:56 UTC, guilpier-code commented on src/libs/antares/study/runtime/runtime.cpp
> +void StudyRuntimeInfos::initializeInequalityBindingConstraints()
Do we initialize, here ? I guess we rather store inequality binding constraints numbers, do we not ?
If so, I suggest we call this method **getInequalityBindingConstraintsNumbers()**. 
We do not need to store these numbers, so we just have to return them (vector<uint>)

2022-09-06 14:56 UTC, guilpier-code commented on src/solver/variable/bindConstraints.hxx
> +    const std::vector<uint>& InequalityBCnumbers = study.runtime->bindingConstraintGlobalNumbers;
I'm not at ease with getting a data directly in the runtime class like this.
According to remarks made in source file **runtime.cpp**, we can either have : 
- **getInequalityBindConstraintGlobalNumbers**(study) computing the global numbers and return a vector of them (which it not costly with the vector move constructor)
-  **getInequalityBindConstraintGlobalNumbers**(study) could return a reference to the the global numbers as a data member of runtime class

2022-09-06 14:56 UTC, guilpier-code commented on src/solver/variable/surveyresults/surveyresults.cpp
> +                                 * runtime->bindingConstraintGlobalNumbers.size()));
Same remark as in **bindConstraints.hxx**

2022-09-08 13:18 UTC, guilpier-code requested changes

2022-09-08 13:18 UTC, guilpier-code commented on src/libs/antares/study/runtime/runtime.h
> +    std::vector<uint> bindingConstraintGlobalNumbers;
**bindingConstraintGlobalNumbers** seems unused

2022-09-08 15:46 UTC, flomnes commented
@guilpier-code DONE

2022-09-08 15:47 UTC, flomnes commented
@guilpier-code DONE

2022-09-08 16:10 UTC, guilpier-code approved these changes

2022-09-08 16:12 UTC, merged