Use average for variable MARG. COST (links)
AntaresSimulatorTeam/Antares_Simulator pull request #881
Opened 2022-09-26 15:41 UTC by flomnes

2022-09-26 16:01 UTC, guilpier-code requested changes

2022-09-26 16:01 UTC, guilpier-code commented on src/solver/variable/economy/links/marginalCost.h
> +        spatialAggregate = Category::spatialAggregateAverage,
Are you sure about that ? To me, this change is about districts : you change the way that area variables are aggregated in a district, it seems. As a matter of fact, this change should not have any effect, as the current variable is related to links. 

Maybe more something like that ? : 
```C++
void yearEnd(unsigned int year, unsigned int numSpace)
{
    // Here is the change I would try
    pValuesForTheCurrentYear[numSpace].computeAVGstatisticsForCurrentYear();

    NextType::yearEnd(year, numSpace);
}
```

2022-09-26 19:19 UTC, flomnes commented on src/solver/variable/economy/links/marginalCost.h
> +        spatialAggregate = Category::spatialAggregateAverage,
@guilpier-code Tested & approved ! DONE

2022-09-27 13:25 UTC, guilpier-code approved these changes

2022-09-28 07:36 UTC, merged