[TEST] Refactoring study's loader
AntaresSimulatorTeam/Antares_Simulator pull request #893
Opened 2022-10-06 07:47 UTC by kathvargasr

2022-10-26 08:33 UTC, flomnes requested changes
- Function `Study::internalLoadFromFolder` is still way too long, consider cutting it into smaller functions

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/load-params.cpp
> +    }
This class only uses `study.areas`. I recommend saving a reference to this object instead.

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/load-params.cpp
> +    }
mark as `const`

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
>      std::map<std::string, uint> table;
- No need for `std::strings` in the `std::map`, just use `Antares::Data::NumberOfCoresMode` as a key, so at line 437, you can use `table.at(parameters.nbCores.ncMode)`. Don't forget to `catch` exception [`std::out_of_range`](https://en.cppreference.com/w/cpp/error/out_of_range)
- `table["min"]` is always equal to `1`, so you may place it before the `switch..case` block
- Move line 331 (`logs.fatal() << ...`) to `case 0` in the `switch..case` block

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
> +    auto& p = parameters;
`const`

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
> +bool Study::allSetsParallelYearsHaveSameSize(const std::vector<std::vector<uint>> setsOfParallelYears){
```suggestion
bool Study::allSetsParallelYearsHaveSameSize(const std::vector<std::vector<uint>>& setsOfParallelYears){
```

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
> +    {
```suggestion
    if (parameters.initialReservoirLevels.iniLevels == Antares::Data::irlHotStart
        && !setsOfParallelYears.empty() && maxNbYearsInParallel > 1)
    {
```

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
> +        if (setsOfParallelYears.size() > 1)
This condition is already checked at line 560

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
> +        maxNbYearsInParallel = nbYearsParallelForced;
Don't call `getNbYearsParallelRaw` in this case, since its results are overridden ?

2022-10-26 08:33 UTC, flomnes commented on src/libs/antares/study/study.cpp
> +    // minNbYearsInParallel_save = minNbYearsInParallel;
Remove commented-out code

2022-10-26 08:33 UTC, flomnes commented on src/tests/src/libs/antares/study/loader/CMakeLists.txt
> +)
Fix formatting here

2022-10-26 08:33 UTC, flomnes commented on src/tests/src/libs/antares/study/loader/test-study-load-internal.cpp
> +// #include "files-generator.h"
Remove this commented-out line

2022-10-28 16:40 UTC, flomnes requested changes

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/CMakeLists.txt
> +add_subdirectory(loader)
study-loader

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +    }
Added for tests, not tested though. Either remove from this [attorney class](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Friendship_and_the_Attorney-Client), or test.

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +    //@}
Same as above

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +
Include at top ? Or don't include

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +using pStudy = std::shared_ptr<Study>;
`Study::Ptr` is already an alias to `shared_ptr<Study>`

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +    using Ptr = std::shared_ptr<StudyWrapper>;
Not needed in my opinion. This object can be allocated on the stack

2022-10-28 16:40 UTC, flomnes commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +
**study-wrapper.h** isn't part of any CMakeFile. It may result in an incomplete dependency graph.

2022-11-14 14:30 UTC, guilpier-code commented
Why not leave a clear introduction to the work ? Ok, I often forget it but it's still useful

2022-11-15 13:30 UTC, guilpier-code requested changes

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/study.cpp
> +    table[ncMin] = 1;
We should rename **table** into **number_of_MC_year_threads** (for instance), table is meaningless.
Besides, **uint** in `std::map<NumberOfCoresMode, uint>` is overstated. **int** is enough.

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/study.cpp
> +    maxNbYearsInParallel = getNbYearsParallelRaw();
Why not : 
```C++
   maxNbYearsInParallel = computeRawNbParallelYear(options.forceParallel, options.maxNbYearsInParallel);
```
?

2022-11-15 13:30 UTC, guilpier-code commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +using pStudy = std::shared_ptr<Study>;
And **pStudy** is very often (if not every time) a class data member variable that contains an instance of Study, not a type as here. There can be a confusion.

2022-11-15 13:30 UTC, guilpier-code commented on src/tests/src/libs/antares/study/wrappers/study-wrapper.h
> +class StudyWrapper
What is the point of this study wrapper ? (It may have a real benefit, but I can't see which one)

I can see that this wrapper is only used (for now) in the newly created tests. So, if it is meant to be used in the context of tests, maybe we should move it next to the tests.

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/study.cpp
> +#include <string>
`#include <string>` : is it useful ?

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/study.cpp
> +void Study::computeRawNbParallelYear(const bool forceParallel, const uint nbYearsParallelForced)
In this file, all changes are related to parallel MC years, right ?
We could try to extract all the logic (computing sets of parallel years) from the study, in order to : 
- empty a little bit the god class **Study**. Said in another way, it would the number of responsibilities of **Study**
- this extracted code could be tested in isolation.
- avoid currently existing code duplication with **solver.hxx** : **buildSetsOfParallelYears(...)**

We could have something like : 
```C++
class setsOfParallelYearsCalculator // Or some name more accurate
{
public:
     setsOfParallelYearsCalculator (
             int nbYears,
             bool userPlaylist,
             int timeSeriesToGenerate,
             int timeSeriesToRefresh,
             bool forceParallel,
             int forcedNbOfParallelYears // Today called "maxNbYearsInParallel"
             );
     void build(); // Main function, it would do what "computeNumberOfCores" does
     bool allSetsParallelYearsHaveSameSize();
private:
     // Private methods
     computeRawNbParallelYear();
     computeMinNbYearsInParallelYearSet();
     
     // Private data members
     std::vector<std::vector<uint>> setsOfParallelYears_;
}
```
**Note** : 
- In this proposal, the class does not take the whole object **parameters** as an argument for its constructor. Instead, we would pass the constructor exactly the list of data it really needs. Indeed, class parameters can be split or can change. The data we give won't.
-

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/load-params.cpp
> +    uint size(Study::SingleSetOfAreas& set) const
`uint size(Study::SingleSetOfAreas& set) const` : I don't see the point of this function.
Instead of calling `sets_of_areas_handler.size(set_of_areas)`, let's simply call `sets_of_areas.size()`

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/load-params.cpp
> +class SetHandlerAreas
Each method of class **SetHandlerAreas** is given a `SingleSetOfAreas& set` (which is a `std::set<Area*>`), and makes something with this argument.
Why not put the **set** in the class and rename the class **setOfAreas** ?
There would be some side effects to that change : it will bring some other changes in the code.
It remains to evaluate the size of these changes.

2022-11-15 13:30 UTC, guilpier-code commented on src/libs/antares/study/load-params.cpp
> +bool Study::initializeInternalData(const StudyLoadOptions& options)
Apparently, method **initializeInternalData** does 3 (at least) things : 
- it initializes **parameters** (it should be done by a method of class **Parameters**, or better : in the **Parameters** constructor, if possible)
- it initializes the calendar (same remark as above, with class **Date::Calendar**)
- it makes a check (should be moved with other checks : to be explored)

Each bullet should be separated from the others in a function / method
This split would have few consequences **test-study-load-internal.cpp**.

2023-01-05 09:57 UTC, kathvargasr commented
replaced by #1017 and  #1057

2023-01-05 09:57 UTC, closed without merging